image: docker:stable

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t "$DOCKER_USERNAME"/"$IMAGE_NAME" .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/"$IMAGE_NAME"