INSERT INTO product (id, name, price, stock, id_category) VALUES ('1027', 'Corsair K70 RGB MK.2 Mechanical Gaming Keyboard Cherry MX Red Switches: Linear and Fast, Per Key Multi-Colour RGB Backlighting, Aluminium Chassis, QWERTY UK Layout - Black', '149.99', '432', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1045', '[Updated Version] Wireless Mouse, Patuoxun 2.4G USB Wireless Mice Optical PC Laptop Computer Cordless Mouse with Nano Receiver, 6 Buttons, 2400 DPI 5 Adjustment Levels for Windows Mac Macbook Linux - Super Energy Saving, Black', '8.29', '18', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1124', 'ADMi Gaming PC: G4560, GTX 1050 Ti 4GB, 8GB DDR4, 1TB HDD, Wifi, Windows 10', '499.95', '216', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1125', 'The Stone Roses', '16.99', '459', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1137', 'Wireless Mouse, 【Slim & Noiseless】Patuoxun 2.4G USB PC Laptop Computer Cordless Mice with Nano Receiver, 1600 DPI Mouse,Home & Office for Windows Mac Linux Vista Macbook-Super Energy Saving, Black', '7.99', '256', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1144', 'DELL OPTIPLEX 780 DESKTOP CORE 2 QUAD 2.4GHZ 4GB 160GB 22" MONITOR WINDOWS 10 64BIT Certified Refurbished', '24.90', '162', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1179', 'Logitech K380 Multi-Device Bluetooth Keyboard for Windows, Mac, Chrome, Android, iOS and Apple TV - QWERTY, UK Layout, Black', '24.99', '488', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1374', 'Lenovo IdeaPad 320 15.6" HD Notebook - Platinum Grey Intel Pentium Gold 2.3GHz 4415U, 4GB RAM, 2TB HDD, Windows 10 Home', '299.99', '24', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1376', 'HP ENVY 13-ah0001na 13.3-Inch FHD Touch Screen Laptop - Silver Intel i5-8250U, 8 GB RAM, 256 GB SSD, NVIDIA GeForce MX150, 2 GB Dedicated, Windows 10 Home', '799.00', '202', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1386', 'Logitech M185 Wireless Mouse for Windows, Mac and Linux - Grey', '9.99', '395', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1388', 'Beelink BT3Pro Windows 10 Multi Media Desktop Full 4K HD H.265 Smart Mini PC Intel Atom x5-Z8350 Processor 4GB+64G / 4K / 1000Mbps LAN / HDMI / VGA / 2.4G+5.8G Dual WiFi', '129.90', '149', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1396', 'The Stone Roses', '16.99', '150', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1400', 'Macally SLIMKEYPROA-UK 104 key British English Layout Ultra Slim and Full Size USB Keyboard for Mac', '38.95', '80', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('150', 'New HP Quad Turbo 3.0*GHz Laptop Radeon R4 Graphics-1TB HDD-Fast 4GB DDR4 Ram + Win10 Pro + Office Pro + Warranty', '448.44', '352', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1618', 'Ultimate Collection', '7.88', '66', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1630', 'ASUS VivoBook E201NA-GJ008T-OSS 11.6 Inch HD Notebook - Blue/Grey Intel Celeron Dual Core N3350, 4 GB RAM, 64 GB eMMC, Windows 10', '159.99', '371', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1638', 'Microsoft Wired Keyboard 600, UK Layout - Black', '10.48', '426', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1647', 'ADMI VR-1 Gaming PC: AMD Ryzen 2300X 4.0Ghz Quad Core, RX570 4GB Graphics Card, 8GB 2400MHz DDR4, 1TB HDD, Raider RGB Glass Case, Windows 10, 300mbps Wifi', '549.95', '306', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1661', 'Paul Simon - The Ultimate Collection', '5.00', '264', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1662', 'HP Elite 8300 SFF Quad Core i5-3470 3.2GHz 8GB 1000GB DVD WiFi Windows 10 Professional Desktop PC Computer Certified Refurbished View', '168.80', '359', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1734', 'For Ever', '10.30', '356', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1744', 'HP Stream 14-ax005na 14-inch HD Laptop Smoke Grey - Intel Celeron N3060, 4 GB RAM, 32 GB eMMC, 1 TB OneDrive and Office 365, 1-Year Subscription Included, Intel HD Graphics, Windows 10', '212.27', '381', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1754', 'ADMI Gaming PC: AMD A10-9700 3.8GHz Quad Core, Radeon R7 Graphics, 1TB HDD, 8GB DDR4 RAM, 300Mbps Wifi, Windows 10', '309.95', '123', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1773', 'Greatest', '4.99', '309', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1793', 'Automatic for the People', '18.02', '75', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1816', 'HP Stream 14-cb007na 14 Inch Laptop, Aqua Blue Intel Celeron N3060, 4 GB RAM, 32 GB eMMC, Office 365 and 1 TB OneDrive Cloud Storage, 1 Year Subscription Included , Windows 10 Home', '249.00', '430', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1823', 'Logitech K780 Multi-Device Wireless USB, Bluetooth Keyboard, Wireless Keyboard for Windows, Mac, Chrome OS, iOS, Android, Switch Between Devices, Quiet Keyboard, QWERTY UK Layout, Dark Gray/White', '50.00', '309', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1849', 'HP 14-bw021na 14-Inch Laptop AMD Dual-Core A6-9220 APU 2.9GHz, 8GB RAM, 1TB HDD, AMD Radeon R4 Graphics, Windows 10 - White', '329.99', '78', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1870', 'ASUS X540NA-GQ232T 15.6 Inch HD Laptop - Chocolate Black Intel Pentium N4200, 4 GB RAM, 1 TB HDD, Windows 10', '249.99', '132', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1880', '+', '5.40', '258', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('192', 'Music For Mindfulness', '4.85', '444', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1921', 'ACEPC Mini PC,Intel x5-Z8350 HD Graphics Desktop Computer, Windows 10 Pro 64-bit, DDR3L 2GB/32GB eMMC/4K/Built-in Dual WiFi 2.4G /5.0G /BT 4.0', '89.99', '52', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1982', 'Logitech B100 Optical USB Ambidextrous Mouse for Windows, Mac and Linux - Black', '6.86', '47', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('1997', 'Acer Chromebook 14 CB3-431 - Intel Celeron N3160, 4GB RAM, 32GB eMMC, 14 inch FHD Display, Google Chrome OS, Silver', '249.00', '277', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2033', 'Jelly Comb Bluetooth Keyboard, KUS-009C Wireless Compact Aluminum Keyboard UK Layout QWERTY Ultra Slim Rechargeable Bluetooth Devices, White + Silver', '21.99', '198', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2034', 'Ultimate Sinatra', '8.85', '230', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2095', 'ADMi Gaming PC: G4560, GTX 1050 Ti 4GB, 8GB DDR4, 1TB HDD, Wifi, Windows 10', '499.95', '188', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2120', 'Dell Chromebook 11 3000 11.6 Inch Notebook -Black Intel Celeron N3060, 4 GB RAM, 16 GB eMMC, Chrome OS', '24.90', '241', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2128', 'Microsoft Wireless Desktop 2000 Keyboard and Mouse Set, UK Layout - Black', '30.24', '337', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2137', 'The 1975', '20.49', '319', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2195', 'Music for The Jilted Generation', '6.84', '345', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2217', 'As Long As I Have You', '4.56', '481', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2218', 'Lenovo ThinkPad T430 i5-3320M 2.6GHz 8GB RAM, 256GB SSD DVDRW 14.1 WXGA++ 1600x900 Webcam Windows 10 Pro 64 bit WiFi Grade A  Renewed', '24.90', '457', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2230', 'Logitech M570 Wireless Mouse Trackball for Windows, Mac UK Model - Black', '32.74', '98', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2237', 'The Beach Boys With The Royal Philharmonic Orchestra', '4.99', '183', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2243', 'Logitech M570 Wireless Mouse Trackball for Windows, Mac UK Model - Black', '32.74', '235', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2298', 'NOW That¿s What I Call Rock Ballads', '7.40', '375', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('231', 'HP EliteBook 840 G1 14-inch Ultrabook Intel Core i5 4th Gen, 8GB Memory, 256GB SSD, WiFi, WebCam, Windows 10 Professional 64-bit Certified Refurbished', '315.00', '276', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2349', 'EMPIRE GAMING – WarFare PC Gaming unit – Black – Red LED: USB 3.0, 3 x 120 mm LED Fans, Smoked transparent side panel – ATX/mATX / mITX', '43.90', '142', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2361', 'Razer BlackWidow Chroma V2, Tactile and Clicky Mechanical Gaming Keyboard Razer Green Switches, Ergonomic Hand Wrist Rest, RGB Chroma Lighting, Programmable, 5 Macro Keys, UK Layout', '142.48', '434', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2375', 'Rii i8BT Bluetooth Mini Wireless Keyboard with Touchpad Mouse Built-in Rechargeable Battery', '13.99', '29', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2377', 'Concrete and Gold', '4.20', '57', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2391', 'Windows 10, Dell Optiplex Desktop PC, Dual Core, 4GB Ram, 160GB Hard Drive, DVD Certified Refurbished', '60.00', '144', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2425', 'Walls', '10.90', '482', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2433', 'The Music Of Nashville Greatest Hits Seasons 1-6', '14.35', '171', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2464', 'Assume Form', '10.99', '295', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('248', 'HP Stream 14-cb008na 14 Inch Laptop, Violet Purple Intel Celeron N3060, 4 GB RAM, 32 GB eMMC, Office 365 and 1 TB OneDrive Cloud Storage, 1 Year Subscription Included , Windows 10 Home', '207.77', '157', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2616', 'WiFi enabled Complete set of Dell OptiPlex Dual Core Windows 10 Desktop PC Computer Certified Refurbished', '68.00', '274', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2644', 'Perixx PERIBOARD-409U Mini Wired Keyboard - USB - 315x147x21mm - UK Layout', '9.99', '132', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2660', 'APPLE IMAC A1224 "CORE 2 DUO" 2.0 -2.4GHZ, 4GB RAM, 160GB HDD, 20" SCREEN, OS X EL CAPITAN  Refurbished', '179.00', '374', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2675', 'Beelink BT3Pro Windows 10 Multi Media Desktop Full 4K HD H.265 Smart Mini PC Intel Atom x5-Z8350 Processor 4GB+64G / 4K / 1000Mbps LAN / HDMI / VGA / 2.4G+5.8G Dual WiFi', '129.90', '312', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2707', 'WiFi enabled Complete set of Dell OptiPlex Dual Core Windows 10 Desktop PC Computer Certified Refurbished', '68.00', '496', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2744', 'CiT OEM Scroller USB Brown Box Optical Mouse - Black', '3.72', '485', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2770', 'Music for The Jilted Generation', '6.84', '481', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2771', 'Love Yourself Answer', '12.49', '90', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2780', 'This Land', '11.39', '94', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2820', 'Dell OptiPlex 7010 SFF Core i3 8GB 1TB DVDRW WiFi Windows 10 Professional 64-Bit Desktop PC Computer With Antivirus Certified Refurbished', '178.00', '472', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2833', 'USB Keyboard Wired【Comfortable & Durable】VicTsing Full Size Keyboard with 105 Chiclet Keys Quick Responsive, Plug and Play for Laptop, PC, Computer Windows Mac etc. – UK Layout, Black', '7.99', '145', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2846', 'Acer Chromebook 14 CB3-431 - Intel Celeron N3060, 2GB RAM, 32GB eMMC, 14 inch HD Display, Google Chrome OS, Silver', '214.99', '137', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2876', 'ASUS E203MA-FD001TS 11.6 Inch Laptop - Star Grey Intel Celeron N4000 Processor, 2 GB RAM, 32 GB eMMC + 2 Years of 500 GB Free Web Storage, Pre-Installed with Microsoft Office 365, Windows 10', '159.99', '372', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2915', 'Dreamboats & Petticoats - The Diamond Edition', '6.28', '472', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('2962', 'Dell Inspiron 15 3000 15.6 Inch FHD Laptop Black Intel Core i5-7200U, 4 GB RAM, 1 TB HDD, Windows 10 Home', '399.97', '469', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3005', 'Logitech MX Master AMZ Wireless Bluetooth Mouse, USB Receiver for Windows and Mac, Rechargeable Battery, Multi-Device, Programmable Buttons for Productivity, Graphite', '59.88', '430', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3037', 'I, the Mask inc bonus track', '10.99', '90', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3056', 'Logitech MX Master AMZ Wireless Bluetooth Mouse, USB Receiver for Windows and Mac, Rechargeable Battery, Multi-Device, Programmable Buttons for Productivity, Graphite', '59.88', '209', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3115', 'NOW That’s What I Call Rock’N’Roll', '11.52', '169', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3241', 'Corsair K70 RGB MK.2 Mechanical Gaming Keyboard Cherry MX Speed Switches: Linear and Rapid, Per Key Multicolour RGB Backlighting, Aluminium Chassis, QWERTY UK Layout - Black', '153.99', '44', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3261', 'Logitech Craft Wireless Bluetooth Keyboard for Windows, Mac, Creative Input Dial for Productive and Creative Control, Precision Typing, Rechargeable, Multi-Device Support, QWERTY UK Layout', '99.97', '55', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3283', 'Half Way There', '7.99', '458', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3315', 'Trust 21949 Ziva Optical Wireless Mouse for Computer and Laptop, 1200-1800 DPI, Black', '5.99', '138', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3395', 'The Big Bad Blues', '12.55', '431', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3408', 'Twenty Five - Greatest Hits', '4.45', '495', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3421', 'Lenovo ThinkPad T430 3rd Gen i5-3320M 8GB 128GB SSD WebCam DVDRW USB 3.0 Windows 10 Professional 64-bit Certified Refurbished', '224.00', '249', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3426', 'Moonglow book', '10.99', '173', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3431', '13 Rivers', '11.31', '135', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3480', 'TeckNet Bluetooth Mouse, 3000DPI Wireless Mouse, 24 Month Battery Life With Battery Indicator, 3000/2000/1600/1200/800 dPi', '11.99', '459', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3505', 'TeckNet Wireless Mouse, Omni Mini 2.4G Wireless Portable Mobile Computer Mouse Mice With 18 Month Battery Life, 2000 DPI 3 Adjustment Levels, USB Nano Receiver, Auto Sleeping Design', '5.99', '167', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3521', 'WiFi enabled Complete set of Dell OptiPlex Dual Core Windows 10 Desktop PC Computer Certified Refurbished', '68.00', '270', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3551', 'Asus Chromebit CS10 Rockchip 3288-C, 2 GB RAM, 16 GB eMMC, Chrome OS - Black', '103.63', '256', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3559', 'Live In Buenos Aires', '10.15', '360', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3561', 'Concrete and Gold', '4.20', '277', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3592', 'TeckNet Pro S2 High Performance Wired USB Mouse, 6 Buttons, upto 2000dpi', '6.99', '497', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3652', 'Rii i8+BT LED Backlit Mini Bluetooth Wireless Keyboard with Touchpad Mouse UK Layout with Built-in Rechargeable Battery', '16.99', '99', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3696', 'HP Elite 8300 SFF Quad Core i5-3470 3.2GHz 8GB 1000GB DVD WiFi Windows 10 Professional Desktop PC Computer Certified Refurbished View', '168.80', '67', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3728', '[Updated Version] Wireless Mouse, Patuoxun 2.4G USB Wireless Mice Optical PC Laptop Computer Cordless Mouse with Nano Receiver, 6 Buttons, 2400 DPI 5 Adjustment Levels for Windows Mac Macbook Linux - Super Energy Saving, Black', '8.29', '304', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3773', 'The Big Bad Blues', '12.55', '131', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3866', 'ACEPC Mini PC,Intel x5-Z8350 HD Graphics Desktop Computer, Windows 10 Pro 64-bit, DDR3L 2GB/32GB eMMC/4K/Built-in Dual WiFi 2.4G /5.0G /BT 4.0', '89.99', '301', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3921', 'Walls', '10.90', '277', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('3966', 'Wireless Mouse, Jelly Comb 2.4G Computer Mice with Nano Receiver for PC/Tablet/Laptop and Windows/Mac/Linux, Silent & Smooth, Basic Design Black & Gold', '7.99', '62', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4064', 'Golden', '8.98', '117', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4084', 'WiFi enabled Windows 10 Dell Optiplex Desktop PC, Dual Core, 4GB Ram, 160GB Hard Drive, DVD Certified Refurbished', '69.95', '137', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4124', 'Never Forget The Ultimate Collection', '4.60', '133', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4160', 'Logitech MX Master 2S Multi-Device Bluetooth Wireless Mouse with USB Unifying Receiver and Rechargeable Battery for Mac and Windows, Graphite', '69.99', '331', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4186', 'Dell OptiPlex 7010 SFF Core i3 8GB 1TB DVDRW WiFi Windows 10 Professional 64-Bit Desktop PC Computer With Antivirus Certified Refurbished', '24.90', '112', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4202', 'HP Elite 8300 SFF Quad Core i5-3470 3.20GHz 8GB 256GB SSD DVD WiFi Windows 10 Professional Desktop PC Computer With Antivirus Certified Refurbished', '24.90', '370', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4225', 'Apple Magic Mouse 2', '66.91', '62', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4236', 'Love Yourself: Answer', '12.49', '337', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4266', 'Logitech MX Master 2S Multi-Device Bluetooth Wireless Mouse with USB Unifying Receiver and Rechargeable Battery for Mac and Windows, Graphite', '69.99', '458', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4299', 'Huawei Matebook D 14-Inch Laptop - Mystic Silver Ryzen 5 2500U Processor, 8 GB RAM, 256 GB SSD, Radeon Vega Graphics, Windows 10 Home', '699.00', '228', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4327', '+', '5.40', '307', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4400', 'Microsoft 13.5-inch Touchscreen Surface Laptop - Platinum Intel M-5Y70 Processor, 4 GB RAM, 128 GB SSD, Intel HD 5300 Graphics, Windows 10', '659.00', '227', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4408', 'EMPIRE GAMING – WarFare PC Gaming unit – Black – Blue LED: USB 3.0, 3 x 120 mm LED Fans, Smoked transparent side panel – ATX/mATX / mITX', '43.90', '361', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4417', 'Do the Reggae / Skinhead Reggae in the Spirit of "69', '7.75', '152', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4431', 'Liberation', '9.00', '4', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('45', 'Tranquility Base Hotel & Casino', '8.86', '285', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4526', 'Logitech M185 Wireless Mouse for Windows, Mac and Linux - Red', '24.90', '93', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4708', 'Dell OptiPlex 7010 SFF 3rd Gen Quad Core i5-3470 8GB 128GB SSD DVDRW Windows 10 Professional 64-Bit Desktop PC Computer Certified Refurbished', '185.00', '45', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4745', '14.1" Full HD Windows 10 Laptop - 4GB RAM 32GB Storage, T90B+ Pro Model Lapbook, Intel 64-bit USB 3.0, 5GHz WIFI Dual-Band WIFI 2x WIFI speeds, Supports 256GB tf-card and 1TB HDD T90B+ PRO', '199.97', '46', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4778', 'Weezer Black Album', '9.24', '405', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4780', 'ASUS Chromebook C423 14 Inch HD Notebook - Grey Intel Celeron N3350 Processor, 4 GB RAM, 32 GB eMMC, Chrome OS', '199.00', '386', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4791', 'Bluetooth Wireless Keyboard, VicTsing Portable Keyboard Simple Connect with iPad, Mac, Apple, Tablet, Smart-phone, Android, iOS, Windows etc. - Ultra-Slim, White', '9.59', '313', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4865', 'Weezer Black Album', '9.24', '382', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4904', 'Acer Chromebook R11 CB5-132T - Intel Celeron N3060, 4GB RAM, 32GB eMMC, 11.6 inch HD Touchscreen Display, Google Chrome OS, White', '270.00', '33', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4905', 'Distance Over Time Ltd.', '14.69', '391', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4915', 'Dell Inspiron 15 3000 15.6 Inch HD Anti-Glare LED-Backlit 2019 Laptop - Black Intel Core i3-7020U, 8 GB RAM, 1 TB HDD, Windows 10 Home', '429.99', '214', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4935', 'Logitech Wireless Keyboard K270 - UK layout', '24.97', '216', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4957', 'Music for The Jilted Generation', '6.84', '344', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4958', 'Anker® 2.4G Wireless Vertical Ergonomic Optical Mouse, 800/1200 /1600DPI, 5 Buttons - Black', '13.99', '492', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('4971', 'Logitech G513 RGB Backlit Mechanical Gaming Keyboard with Romer-G Tactile Key Switches UK Layout - Carbon', '99.99', '351', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('516', 'Logitech K120 Keyboard for Windows and Linux - QWERTY, UK Layout', '12.82', '69', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('591', 'Brave', '7.68', '11', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('61', 'KIDZ BOP Summer "18', '4.85', '9', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('641', 'Huawei Matebook X PRO 13.9" Laptop Grey 3k TouchScreen- 35.3 centimeters LCD Laptop Grey - Intel 8th Generation i7-8550U 1.8 GHz, 8 GB RAM, 512GB SDD, Geforce MX150, Windows 10 Pro', '1440.76', '201', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('665', 'The Beach Boys With The Royal Philharmonic Orchestra', '4.99', '39', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('679', 'HP Stream 11-ah005na 11.6 Inch Laptop Aqua Blue - Intel Celeron N3060, 2 GB RAM, 32 GB eMMC, Office 365 and 1 TB OneDrive Cloud Storage with 1 Year Subscription, Windows 10 Home', '149.99', '295', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('685', 'ADMI Gaming PC: i7 8700, RTX 2060, 16GB 2400MHz, 240GB SSD, 2TB HDD, MB520 Case, 550W PSU, Wifi, Windows 10', '999.95', '71', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('747', 'APPLE IMAC A1224 "CORE 2 DUO" 2.0 -2.4GHZ, 4GB RAM, 1TB HDD, 20" SCREEN, OS X EL CAPITAN  Refurbished', '199.99', '451', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('77', 'I, the Mask inc bonus track', '10.99', '365', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('775', 'ASUS C302CA-GU010 360 Degrees Rotatable Full HD Touchscreen Chromebook Flip 12.5 Inch Notebook - Black Intel Core M3-6Y30 Processor, 4 GB RAM, 64 GB eMMC, Chrome OS', '24.90', '112', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('80', 'Wireless Mouse, VicTsing 2.4G Slim Noiseless USB Laptop PC Computer Cordless Mouse with Nano Receiver with Extra Long Range for Windows Mac Linux Vista MacBook, Super Energy Saving, Black', '7.99', '3', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('824', 'Windows 10, Dell Optiplex Desktop PC, Dual Core, 4GB Ram, 160GB Hard Drive, DVD Certified Refurbished', '60.00', '495', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('858', 'Lenovo IdeaPad 320-15IKBRN 15.6-Inch HD Notebook - Platinum Grey Intel Core i5-8250U, 4 GB RAM, 128 GB SSD, Windows 10 Home', '429.98', '133', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('884', 'The Big Bad Blues', '12.55', '76', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('92', 'Logitech G305 Wireless Gaming Mouse with Hero Sensor DPI, Lightweight, PC Gaming, Tunable with 6 Programmable Buttons, Long Battery Life, compatible with Windows, Mac and Chrome OS - EU Package', '33.99', '220', '2') ;
INSERT INTO product (id, name, price, stock, id_category) VALUES ('937', 'Half Way There', '7.99', '209', '2') ;
