INSERT INTO specification_body (id, content) VALUES ('360', '1') ;
INSERT INTO specification_body (id, content) VALUES ('361', '2') ;
INSERT INTO specification_body (id, content) VALUES ('362', '3') ;
INSERT INTO specification_body (id, content) VALUES ('363', '4') ;
INSERT INTO specification_body (id, content) VALUES ('124', '21949') ;
INSERT INTO specification_body (id, content) VALUES ('125', '74940') ;
INSERT INTO specification_body (id, content) VALUES ('138', '75002') ;
INSERT INTO specification_body (id, content) VALUES ('129', '713368') ;
INSERT INTO specification_body (id, content) VALUES ('77', '765489') ;
INSERT INTO specification_body (id, content) VALUES ('128', '842949') ;
INSERT INTO specification_body (id, content) VALUES ('126', '848361') ;
INSERT INTO specification_body (id, content) VALUES ('0', '1.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('1', '90.7 g') ;
INSERT INTO specification_body (id, content) VALUES ('2', '599 g') ;
INSERT INTO specification_body (id, content) VALUES ('3', '259 g') ;
INSERT INTO specification_body (id, content) VALUES ('4', '9.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('5', '300g') ;
INSERT INTO specification_body (id, content) VALUES ('6', '59 g') ;
INSERT INTO specification_body (id, content) VALUES ('7', '16.4 kg') ;
INSERT INTO specification_body (id, content) VALUES ('8', '159 g') ;
INSERT INTO specification_body (id, content) VALUES ('9', '522 g') ;
INSERT INTO specification_body (id, content) VALUES ('10', '281 g') ;
INSERT INTO specification_body (id, content) VALUES ('11', '2.6 kg') ;
INSERT INTO specification_body (id, content) VALUES ('12', '2.4 kg') ;
INSERT INTO specification_body (id, content) VALUES ('13', '780 g') ;
INSERT INTO specification_body (id, content) VALUES ('14', '81.6 g') ;
INSERT INTO specification_body (id, content) VALUES ('15', '12.2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('16', '621 g') ;
INSERT INTO specification_body (id, content) VALUES ('17', '8.4 kg') ;
INSERT INTO specification_body (id, content) VALUES ('18', '2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('19', '10.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('20', '68 g') ;
INSERT INTO specification_body (id, content) VALUES ('21', '2.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('22', '1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('23', '989 g') ;
INSERT INTO specification_body (id, content) VALUES ('24', '322 g') ;
INSERT INTO specification_body (id, content) VALUES ('25', '240 g') ;
INSERT INTO specification_body (id, content) VALUES ('26', '181 g') ;
INSERT INTO specification_body (id, content) VALUES ('27', '118 g') ;
INSERT INTO specification_body (id, content) VALUES ('28', '2.3 kg') ;
INSERT INTO specification_body (id, content) VALUES ('29', '1.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('30', '331 g') ;
INSERT INTO specification_body (id, content) VALUES ('31', '458 g') ;
INSERT INTO specification_body (id, content) VALUES ('32', '3 kg') ;
INSERT INTO specification_body (id, content) VALUES ('33', '200 g') ;
INSERT INTO specification_body (id, content) VALUES ('34', '998 g') ;
INSERT INTO specification_body (id, content) VALUES ('35', '499 g') ;
INSERT INTO specification_body (id, content) VALUES ('36', '40.8 g') ;
INSERT INTO specification_body (id, content) VALUES ('37', '5.5 kg') ;
INSERT INTO specification_body (id, content) VALUES ('38', '2.2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('39', '340 g') ;
INSERT INTO specification_body (id, content) VALUES ('40', '676 g') ;
INSERT INTO specification_body (id, content) VALUES ('41', '7 kg') ;
INSERT INTO specification_body (id, content) VALUES ('42', '662 g') ;
INSERT INTO specification_body (id, content) VALUES ('43', '16.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('44', '18.1 g') ;
INSERT INTO specification_body (id, content) VALUES ('45', '10 kg') ;
INSERT INTO specification_body (id, content) VALUES ('46', '6.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('47', '540 g') ;
INSERT INTO specification_body (id, content) VALUES ('48', '1.6 kg') ;
INSERT INTO specification_body (id, content) VALUES ('49', '3.2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('50', '299 g') ;
INSERT INTO specification_body (id, content) VALUES ('51', '31.8 g') ;
INSERT INTO specification_body (id, content) VALUES ('52', '381 g') ;
INSERT INTO specification_body (id, content) VALUES ('53', '141 g') ;
INSERT INTO specification_body (id, content) VALUES ('54', '581 g') ;
INSERT INTO specification_body (id, content) VALUES ('55', '558 g') ;
INSERT INTO specification_body (id, content) VALUES ('56', '748 g') ;
INSERT INTO specification_body (id, content) VALUES ('57', '7.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('58', '7.9 kg') ;
INSERT INTO specification_body (id, content) VALUES ('59', '2.5 kg') ;
INSERT INTO specification_body (id, content) VALUES ('60', '762 g') ;
INSERT INTO specification_body (id, content) VALUES ('61', '449 g') ;
INSERT INTO specification_body (id, content) VALUES ('62', '862 g') ;
INSERT INTO specification_body (id, content) VALUES ('63', '6.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('64', '327 g') ;
INSERT INTO specification_body (id, content) VALUES ('65', '2.9 kg') ;
INSERT INTO specification_body (id, content) VALUES ('66', '1.9 kg') ;
INSERT INTO specification_body (id, content) VALUES ('67', '1.7 kg') ;
INSERT INTO specification_body (id, content) VALUES ('68', '15 kg') ;
INSERT INTO specification_body (id, content) VALUES ('69', '49.9 g') ;
INSERT INTO specification_body (id, content) VALUES ('70', '776 g') ;
INSERT INTO specification_body (id, content) VALUES ('71', '721 g') ;
INSERT INTO specification_body (id, content) VALUES ('72', 'ch-9109010-uk') ;
INSERT INTO specification_body (id, content) VALUES ('73', 'ca57bn-ukvv1') ;
INSERT INTO specification_body (id, content) VALUES ('74', 'pro-002') ;
INSERT INTO specification_body (id, content) VALUES ('75', '.') ;
INSERT INTO specification_body (id, content) VALUES ('76', 'pagepc079ab-ukaa1') ;
INSERT INTO specification_body (id, content) VALUES ('78', 'k380') ;
INSERT INTO specification_body (id, content) VALUES ('79', '80xl03s8uk') ;
INSERT INTO specification_body (id, content) VALUES ('80', '4ew09ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('81', '910-002225') ;
INSERT INTO specification_body (id, content) VALUES ('82', 'bt3pro') ;
INSERT INTO specification_body (id, content) VALUES ('83', 'slimkeyproa-uk') ;
INSERT INTO specification_body (id, content) VALUES ('84', 'e201na-gj008t-oss') ;
INSERT INTO specification_body (id, content) VALUES ('85', 'anb-00006') ;
INSERT INTO specification_body (id, content) VALUES ('86', 'pro-001') ;
INSERT INTO specification_body (id, content) VALUES ('87', '14-ax005na') ;
INSERT INTO specification_body (id, content) VALUES ('88', 'kjcrcvtakj') ;
INSERT INTO specification_body (id, content) VALUES ('89', '3rn80ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('90', '920-008041') ;
INSERT INTO specification_body (id, content) VALUES ('91', '2458x00140') ;
INSERT INTO specification_body (id, content) VALUES ('92', '2cs90ea') ;
INSERT INTO specification_body (id, content) VALUES ('93', 'x540na-gq232t') ;
INSERT INTO specification_body (id, content) VALUES ('94', 'acepc t8') ;
INSERT INTO specification_body (id, content) VALUES ('95', 'rock0813') ;
INSERT INTO specification_body (id, content) VALUES ('96', 'e92bo1nkak') ;
INSERT INTO specification_body (id, content) VALUES ('97', '910-003357') ;
INSERT INTO specification_body (id, content) VALUES ('98', 'nx.gc2ek.007') ;
INSERT INTO specification_body (id, content) VALUES ('99', 'signature pro') ;
INSERT INTO specification_body (id, content) VALUES ('100', 'aud athad500x') ;
INSERT INTO specification_body (id, content) VALUES ('101', 'xf8rm') ;
INSERT INTO specification_body (id, content) VALUES ('102', 'm7j-00020') ;
INSERT INTO specification_body (id, content) VALUES ('103', 'thinkpad t430') ;
INSERT INTO specification_body (id, content) VALUES ('104', '910-001882') ;
INSERT INTO specification_body (id, content) VALUES ('105', 'aud athe40') ;
INSERT INTO specification_body (id, content) VALUES ('106', 'ath-avc200') ;
INSERT INTO specification_body (id, content) VALUES ('107', 'oe-ca-11re') ;
INSERT INTO specification_body (id, content) VALUES ('108', 'rz03-02030400-r3w1') ;
INSERT INTO specification_body (id, content) VALUES ('109', 'hpx2000') ;
INSERT INTO specification_body (id, content) VALUES ('110', 'mini i8bt mini bluetooth keyboard') ;
INSERT INTO specification_body (id, content) VALUES ('111', '2470x00190') ;
INSERT INTO specification_body (id, content) VALUES ('112', '3rn81ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('113', '2058x00190') ;
INSERT INTO specification_body (id, content) VALUES ('114', 'kmqzmi7ivi') ;
INSERT INTO specification_body (id, content) VALUES ('115', 'k3896jana1') ;
INSERT INTO specification_body (id, content) VALUES ('116', 'ms-scroller') ;
INSERT INTO specification_body (id, content) VALUES ('117', 'nx.gc2ek.003') ;
INSERT INTO specification_body (id, content) VALUES ('118', 'e203ma-fd001ts') ;
INSERT INTO specification_body (id, content) VALUES ('119', '4yr34') ;
INSERT INTO specification_body (id, content) VALUES ('120', '910-005313') ;
INSERT INTO specification_body (id, content) VALUES ('121', 'jh-811') ;
INSERT INTO specification_body (id, content) VALUES ('122', 'ch-9109014-uk') ;
INSERT INTO specification_body (id, content) VALUES ('123', '920-008503') ;
INSERT INTO specification_body (id, content) VALUES ('127', 'chromebit-b004c') ;
INSERT INTO specification_body (id, content) VALUES ('130', 'i8+bt mini wireless bluetooth keyboard') ;
INSERT INTO specification_body (id, content) VALUES ('131', 'k92') ;
INSERT INTO specification_body (id, content) VALUES ('132', 'ath-anc700btbk') ;
INSERT INTO specification_body (id, content) VALUES ('133', 'cp003473') ;
INSERT INTO specification_body (id, content) VALUES ('134', '03sg5w3ammbi') ;
INSERT INTO specification_body (id, content) VALUES ('135', '910-005139') ;
INSERT INTO specification_body (id, content) VALUES ('136', 'mulq6tz9lu') ;
INSERT INTO specification_body (id, content) VALUES ('137', '53010fhs') ;
INSERT INTO specification_body (id, content) VALUES ('139', 'rp-dj1200e-k') ;
INSERT INTO specification_body (id, content) VALUES ('140', 'dap-00009') ;
INSERT INTO specification_body (id, content) VALUES ('141', 'fhrumebi85a') ;
INSERT INTO specification_body (id, content) VALUES ('142', 'm185') ;
INSERT INTO specification_body (id, content) VALUES ('143', 'srh840') ;
INSERT INTO specification_body (id, content) VALUES ('144', 't90b+ pro') ;
INSERT INTO specification_body (id, content) VALUES ('145', 'c423na-bv0078') ;
INSERT INTO specification_body (id, content) VALUES ('146', 'fcbfqhqo146') ;
INSERT INTO specification_body (id, content) VALUES ('147', 'hf150') ;
INSERT INTO specification_body (id, content) VALUES ('148', 'nx.g54ek.005') ;
INSERT INTO specification_body (id, content) VALUES ('149', 'fba_920-003745') ;
INSERT INTO specification_body (id, content) VALUES ('150', 'ak-98anwvm-uba') ;
INSERT INTO specification_body (id, content) VALUES ('151', '920-008867') ;
INSERT INTO specification_body (id, content) VALUES ('152', 'fba_920-002501') ;
INSERT INTO specification_body (id, content) VALUES ('153', 'mach-w29') ;
INSERT INTO specification_body (id, content) VALUES ('154', 'tscoazfba001') ;
INSERT INTO specification_body (id, content) VALUES ('155', '3rn89ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('156', 'ad-39e-790-1070-850-w10') ;
INSERT INTO specification_body (id, content) VALUES ('157', 'c302ca-gu010') ;
INSERT INTO specification_body (id, content) VALUES ('158', 'vt-0412-lm') ;
INSERT INTO specification_body (id, content) VALUES ('159', '81bg00c8uk') ;
INSERT INTO specification_body (id, content) VALUES ('160', '910-005283') ;
INSERT INTO specification_body (id, content) VALUES ('161', 'e5athr70x') ;
INSERT INTO specification_body (id, content) VALUES ('162', 'hpx4000') ;
INSERT INTO specification_body (id, content) VALUES ('163', 'corsair') ;
INSERT INTO specification_body (id, content) VALUES ('164', 'patuoxun') ;
INSERT INTO specification_body (id, content) VALUES ('165', 'oneodio') ;
INSERT INTO specification_body (id, content) VALUES ('166', 'limson') ;
INSERT INTO specification_body (id, content) VALUES ('167', 'admi') ;
INSERT INTO specification_body (id, content) VALUES ('168', 'the stone roses') ;
INSERT INTO specification_body (id, content) VALUES ('169', 'dell') ;
INSERT INTO specification_body (id, content) VALUES ('170', 'drymartine') ;
INSERT INTO specification_body (id, content) VALUES ('171', 'logitech') ;
INSERT INTO specification_body (id, content) VALUES ('172', 'emopeak') ;
INSERT INTO specification_body (id, content) VALUES ('173', 'lenovo') ;
INSERT INTO specification_body (id, content) VALUES ('174', 'hp') ;
INSERT INTO specification_body (id, content) VALUES ('175', 'yuancin') ;
INSERT INTO specification_body (id, content) VALUES ('176', 'macally') ;
INSERT INTO specification_body (id, content) VALUES ('177', 'kz') ;
INSERT INTO specification_body (id, content) VALUES ('178', 'the small faces') ;
INSERT INTO specification_body (id, content) VALUES ('179', 'asus') ;
INSERT INTO specification_body (id, content) VALUES ('180', 'microsoft') ;
INSERT INTO specification_body (id, content) VALUES ('181', 'paul simon') ;
INSERT INTO specification_body (id, content) VALUES ('182', 'jungle') ;
INSERT INTO specification_body (id, content) VALUES ('183', 'duran duran') ;
INSERT INTO specification_body (id, content) VALUES ('184', 'alangduo') ;
INSERT INTO specification_body (id, content) VALUES ('185', 'r.e.m.') ;
INSERT INTO specification_body (id, content) VALUES ('186', 'akg') ;
INSERT INTO specification_body (id, content) VALUES ('187', 'ed sheeran') ;
INSERT INTO specification_body (id, content) VALUES ('188', 'various artists') ;
INSERT INTO specification_body (id, content) VALUES ('189', 'acepc') ;
INSERT INTO specification_body (id, content) VALUES ('190', 'rockpapa') ;
INSERT INTO specification_body (id, content) VALUES ('191', 'khanka') ;
INSERT INTO specification_body (id, content) VALUES ('192', 'acer') ;
INSERT INTO specification_body (id, content) VALUES ('193', 'ultrasone') ;
INSERT INTO specification_body (id, content) VALUES ('194', 'audio-technica') ;
INSERT INTO specification_body (id, content) VALUES ('195', 'jelly comb') ;
INSERT INTO specification_body (id, content) VALUES ('196', 'frank sinatra') ;
INSERT INTO specification_body (id, content) VALUES ('197', 'the 1975') ;
INSERT INTO specification_body (id, content) VALUES ('198', 'the prodigy') ;
INSERT INTO specification_body (id, content) VALUES ('199', 'roger daltrey') ;
INSERT INTO specification_body (id, content) VALUES ('200', 'the beach boys') ;
INSERT INTO specification_body (id, content) VALUES ('201', 'audio technica') ;
INSERT INTO specification_body (id, content) VALUES ('202', 'cospor') ;
INSERT INTO specification_body (id, content) VALUES ('203', 'empire gaming') ;
INSERT INTO specification_body (id, content) VALUES ('204', 'razer') ;
INSERT INTO specification_body (id, content) VALUES ('205', 'behringer') ;
INSERT INTO specification_body (id, content) VALUES ('206', 'rii') ;
INSERT INTO specification_body (id, content) VALUES ('207', 'foo fighters') ;
INSERT INTO specification_body (id, content) VALUES ('208', 'fkant') ;
INSERT INTO specification_body (id, content) VALUES ('209', 'barbra streisand') ;
INSERT INTO specification_body (id, content) VALUES ('210', 'nashville cast') ;
INSERT INTO specification_body (id, content) VALUES ('211', 'james blake') ;
INSERT INTO specification_body (id, content) VALUES ('212', 'bestytt') ;
INSERT INTO specification_body (id, content) VALUES ('213', 'perixx') ;
INSERT INTO specification_body (id, content) VALUES ('214', 'apple') ;
INSERT INTO specification_body (id, content) VALUES ('215', 'cit') ;
INSERT INTO specification_body (id, content) VALUES ('216', 'bts') ;
INSERT INTO specification_body (id, content) VALUES ('217', 'gary clark jr.') ;
INSERT INTO specification_body (id, content) VALUES ('218', 'victsing') ;
INSERT INTO specification_body (id, content) VALUES ('219', 'in flames') ;
INSERT INTO specification_body (id, content) VALUES ('220', 'jiuhufh') ;
INSERT INTO specification_body (id, content) VALUES ('221', 'aokey') ;
INSERT INTO specification_body (id, content) VALUES ('222', 'ichoose limited') ;
INSERT INTO specification_body (id, content) VALUES ('223', 'busted') ;
INSERT INTO specification_body (id, content) VALUES ('224', 'trust') ;
INSERT INTO specification_body (id, content) VALUES ('225', 'george michael') ;
INSERT INTO specification_body (id, content) VALUES ('226', 'avantasia') ;
INSERT INTO specification_body (id, content) VALUES ('227', 'richard thompson') ;
INSERT INTO specification_body (id, content) VALUES ('228', 'tecknet') ;
INSERT INTO specification_body (id, content) VALUES ('229', 'coldplay') ;
INSERT INTO specification_body (id, content) VALUES ('230', 'beyerdynamic') ;
INSERT INTO specification_body (id, content) VALUES ('231', 'billy f gibbons') ;
INSERT INTO specification_body (id, content) VALUES ('232', 'bestfy') ;
INSERT INTO specification_body (id, content) VALUES ('233', 'kylie minogue') ;
INSERT INTO specification_body (id, content) VALUES ('234', 'take that') ;
INSERT INTO specification_body (id, content) VALUES ('235', 'huawei') ;
INSERT INTO specification_body (id, content) VALUES ('236', 'aiaiai') ;
INSERT INTO specification_body (id, content) VALUES ('237', 'panasonic') ;
INSERT INTO specification_body (id, content) VALUES ('238', 'christina aguilera') ;
INSERT INTO specification_body (id, content) VALUES ('239', 'hunpta') ;
INSERT INTO specification_body (id, content) VALUES ('240', 'arctic monkeys') ;
INSERT INTO specification_body (id, content) VALUES ('241', 'shure') ;
INSERT INTO specification_body (id, content) VALUES ('242', 'fusion5') ;
INSERT INTO specification_body (id, content) VALUES ('243', 'weezer') ;
INSERT INTO specification_body (id, content) VALUES ('244', 'numark') ;
INSERT INTO specification_body (id, content) VALUES ('245', 'dream theater') ;
INSERT INTO specification_body (id, content) VALUES ('246', 'anker') ;
INSERT INTO specification_body (id, content) VALUES ('247', 'the shires') ;
INSERT INTO specification_body (id, content) VALUES ('248', 'kidz bop kids') ;
INSERT INTO specification_body (id, content) VALUES ('249', 'tscoaz') ;
INSERT INTO specification_body (id, content) VALUES ('250', 'pentium') ;
INSERT INTO specification_body (id, content) VALUES ('251', 'core 2 quad') ;
INSERT INTO specification_body (id, content) VALUES ('252', 'core i5') ;
INSERT INTO specification_body (id, content) VALUES ('253', 'atom') ;
INSERT INTO specification_body (id, content) VALUES ('254', 'a series') ;
INSERT INTO specification_body (id, content) VALUES ('255', 'celeron') ;
INSERT INTO specification_body (id, content) VALUES ('256', 'r series') ;
INSERT INTO specification_body (id, content) VALUES ('257', 'core i7') ;
INSERT INTO specification_body (id, content) VALUES ('258', 'core 2 duo') ;
INSERT INTO specification_body (id, content) VALUES ('259', 'core i3') ;
INSERT INTO specification_body (id, content) VALUES ('260', 'celeron n3350') ;
INSERT INTO specification_body (id, content) VALUES ('261', 'core i7 8550u') ;
INSERT INTO specification_body (id, content) VALUES ('262', 'none') ;
INSERT INTO specification_body (id, content) VALUES ('279', 'intel') ;
INSERT INTO specification_body (id, content) VALUES ('285', 'amd') ;
INSERT INTO specification_body (id, content) VALUES ('265', 'amd®') ;
INSERT INTO specification_body (id, content) VALUES ('266', 'rockchip') ;
INSERT INTO specification_body (id, content) VALUES ('267', 'intel®') ;
INSERT INTO specification_body (id, content) VALUES ('271', 'nvidia geforce gtx 1050 ti') ;
INSERT INTO specification_body (id, content) VALUES ('272', 'integrated') ;
INSERT INTO specification_body (id, content) VALUES ('273', 'uhd graphics') ;
INSERT INTO specification_body (id, content) VALUES ('274', 'amd radeon r4') ;
INSERT INTO specification_body (id, content) VALUES ('275', 'amd rx 570 4gb') ;
INSERT INTO specification_body (id, content) VALUES ('276', 'hd graphics') ;
INSERT INTO specification_body (id, content) VALUES ('277', 'nvidia geforce gtx 900') ;
INSERT INTO specification_body (id, content) VALUES ('278', 'intel hd graphics') ;
INSERT INTO specification_body (id, content) VALUES ('280', 'intel hd graphics 4000') ;
INSERT INTO specification_body (id, content) VALUES ('281', 'intel hd graphics 4400') ;
INSERT INTO specification_body (id, content) VALUES ('282', 'intel hd graphics 2500') ;
INSERT INTO specification_body (id, content) VALUES ('283', 'integrated/on-board graphics') ;
INSERT INTO specification_body (id, content) VALUES ('284', 'intel gma 4500hd') ;
INSERT INTO specification_body (id, content) VALUES ('286', 'intel hd graphics 5300') ;
INSERT INTO specification_body (id, content) VALUES ('287', 'intel hd graphics 500') ;
INSERT INTO specification_body (id, content) VALUES ('288', 'intel hd graphics 610') ;
INSERT INTO specification_body (id, content) VALUES ('289', 'nvidia geforce mx150') ;
INSERT INTO specification_body (id, content) VALUES ('290', 'nvidia rtx 2060 6gb') ;
INSERT INTO specification_body (id, content) VALUES ('291', 'intel uhd graphics 620') ;
INSERT INTO specification_body (id, content) VALUES ('292', '1 tb') ;
INSERT INTO specification_body (id, content) VALUES ('293', '160 gb') ;
INSERT INTO specification_body (id, content) VALUES ('294', '2 tb') ;
INSERT INTO specification_body (id, content) VALUES ('295', '256 gb') ;
INSERT INTO specification_body (id, content) VALUES ('296', '64 gb') ;
INSERT INTO specification_body (id, content) VALUES ('297', '32 gb') ;
INSERT INTO specification_body (id, content) VALUES ('298', '1000 gb') ;
INSERT INTO specification_body (id, content) VALUES ('318', '16 gb') ;
INSERT INTO specification_body (id, content) VALUES ('300', '500gb') ;
INSERT INTO specification_body (id, content) VALUES ('301', '1024 gb') ;
INSERT INTO specification_body (id, content) VALUES ('302', '128 gb') ;
INSERT INTO specification_body (id, content) VALUES ('303', '512 gb') ;
INSERT INTO specification_body (id, content) VALUES ('304', '240 gb') ;
INSERT INTO specification_body (id, content) VALUES ('305', 'hdd 7200 rpm') ;
INSERT INTO specification_body (id, content) VALUES ('306', 'hdd') ;
INSERT INTO specification_body (id, content) VALUES ('307', 'sdd') ;
INSERT INTO specification_body (id, content) VALUES ('308', 'emmc') ;
INSERT INTO specification_body (id, content) VALUES ('309', 'ssd') ;
INSERT INTO specification_body (id, content) VALUES ('310', 'ssd, hdd') ;
INSERT INTO specification_body (id, content) VALUES ('311', 'sata') ;
INSERT INTO specification_body (id, content) VALUES ('312', 'mechanical hard drive') ;
INSERT INTO specification_body (id, content) VALUES ('313', '8 gb') ;
INSERT INTO specification_body (id, content) VALUES ('314', '4 gb') ;
INSERT INTO specification_body (id, content) VALUES ('315', '8192 mb') ;
INSERT INTO specification_body (id, content) VALUES ('316', '2 gb') ;
INSERT INTO specification_body (id, content) VALUES ('317', '4gb') ;
INSERT INTO specification_body (id, content) VALUES ('319', 'compatible with most systems including windows 7 / 8 / 10 / xp, vista 7 / 8, mac and linux. note: side buttons are invalid in mac os') ;
INSERT INTO specification_body (id, content) VALUES ('320', 'windows 10 home') ;
INSERT INTO specification_body (id, content) VALUES ('321', 'windows 10 professional + office pro full version') ;
INSERT INTO specification_body (id, content) VALUES ('322', 'windows 10') ;
INSERT INTO specification_body (id, content) VALUES ('323', 'windows 10/windows 8/windows 8.1/windows 7/windows rt 8.1/windows rt 8') ;
INSERT INTO specification_body (id, content) VALUES ('324', 'windows 10 professional') ;
INSERT INTO specification_body (id, content) VALUES ('325', 'windows 10 pro') ;
INSERT INTO specification_body (id, content) VALUES ('326', 'microsoft windows xp, windows vista, windows 7, linux 2.4 +, mac os x 10.3.9 +') ;
INSERT INTO specification_body (id, content) VALUES ('327', 'chrome os') ;
INSERT INTO specification_body (id, content) VALUES ('328', 'win xp, vista, 7^mac 10.5 +') ;
INSERT INTO specification_body (id, content) VALUES ('329', 'os x el capitan') ;
INSERT INTO specification_body (id, content) VALUES ('330', 'windows xp, vista, 7^mac os x 10.5+^linux kernel 2.6+') ;
INSERT INTO specification_body (id, content) VALUES ('331', 'windows xp/vista/7^linux 2.6+') ;
INSERT INTO specification_body (id, content) VALUES ('332', '15 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('333', '15.6 inches') ;
INSERT INTO specification_body (id, content) VALUES ('334', '33.8 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('335', '29 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('336', '35.6 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('337', '14 inches') ;
INSERT INTO specification_body (id, content) VALUES ('338', '39.624 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('339', '11.6 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('340', '14.10 inches') ;
INSERT INTO specification_body (id, content) VALUES ('341', '20 inches') ;
INSERT INTO specification_body (id, content) VALUES ('342', '35.56 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('343', '29.46 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('344', '39.62 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('345', '34.29 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('346', '35.3 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('347', '11.6 inches') ;
INSERT INTO specification_body (id, content) VALUES ('348', '31.75 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('349', '39.6 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('350', '1366 x 768 pixels') ;
INSERT INTO specification_body (id, content) VALUES ('351', '1920 x 1080') ;
INSERT INTO specification_body (id, content) VALUES ('352', '1366x768') ;
INSERT INTO specification_body (id, content) VALUES ('353', '1366 x 768') ;
INSERT INTO specification_body (id, content) VALUES ('354', '1920x1080') ;
INSERT INTO specification_body (id, content) VALUES ('355', '1600x900') ;
INSERT INTO specification_body (id, content) VALUES ('356', '1920 x 1080 pixels') ;
INSERT INTO specification_body (id, content) VALUES ('357', '2256 x 1504') ;
INSERT INTO specification_body (id, content) VALUES ('358', '3840 x 2160') ;
INSERT INTO specification_body (id, content) VALUES ('359', '3000 x 2000 pixels') ;
INSERT INTO specification_body (id, content) VALUES ('364', 'sony music cmg') ;
INSERT INTO specification_body (id, content) VALUES ('365', 'castle communications') ;
INSERT INTO specification_body (id, content) VALUES ('366', 'xl recordings') ;
INSERT INTO specification_body (id, content) VALUES ('367', 'emi') ;
INSERT INTO specification_body (id, content) VALUES ('368', 'umc') ;
INSERT INTO specification_body (id, content) VALUES ('369', 'atlantic') ;
INSERT INTO specification_body (id, content) VALUES ('370', 'decca umo') ;
INSERT INTO specification_body (id, content) VALUES ('371', 'universal') ;
INSERT INTO specification_body (id, content) VALUES ('372', 'xl') ;
INSERT INTO specification_body (id, content) VALUES ('373', 'polydor') ;
INSERT INTO specification_body (id, content) VALUES ('374', 'now') ;
INSERT INTO specification_body (id, content) VALUES ('375', 'sony music') ;
INSERT INTO specification_body (id, content) VALUES ('376', 'sony commercial group') ;
INSERT INTO specification_body (id, content) VALUES ('377', 'umo') ;
INSERT INTO specification_body (id, content) VALUES ('378', 'import') ;
INSERT INTO specification_body (id, content) VALUES ('379', 'warner bros') ;
INSERT INTO specification_body (id, content) VALUES ('380', 'umod') ;
INSERT INTO specification_body (id, content) VALUES ('381', 'nuclear blast') ;
INSERT INTO specification_body (id, content) VALUES ('382', 'busted lp2') ;
INSERT INTO specification_body (id, content) VALUES ('383', 'sonybmg') ;
INSERT INTO specification_body (id, content) VALUES ('384', 'proper records') ;
INSERT INTO specification_body (id, content) VALUES ('385', 'plg uk frontline') ;
INSERT INTO specification_body (id, content) VALUES ('386', 'snakefarm records') ;
INSERT INTO specification_body (id, content) VALUES ('387', 'bmg rights management uk ltd') ;
INSERT INTO specification_body (id, content) VALUES ('388', 'trojan records') ;
INSERT INTO specification_body (id, content) VALUES ('389', 'rca') ;
INSERT INTO specification_body (id, content) VALUES ('390', 'domino') ;
INSERT INTO specification_body (id, content) VALUES ('391', 'insideoutmusic') ;
INSERT INTO specification_body (id, content) VALUES ('392', 'decca others') ;
INSERT INTO specification_body (id, content) VALUES ('393', 'concord records') ;
INSERT INTO specification_body (id, content) VALUES ('818', '12 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('819', '18 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('820', '4 feb. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('821', '2 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('822', '10 may 2017') ;
INSERT INTO specification_body (id, content) VALUES ('823', '14 april 2014') ;
INSERT INTO specification_body (id, content) VALUES ('824', '17 aug. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('825', '25 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('826', '16 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('827', '3 sept. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('828', '27 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('829', '15 dec. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('830', '21 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('831', '25 jun. 2011') ;
INSERT INTO specification_body (id, content) VALUES ('832', '31 july 2017') ;
INSERT INTO specification_body (id, content) VALUES ('833', '9 aug. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('834', '8 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('835', '14 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('836', '3 mar. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('837', '23 may 2017') ;
INSERT INTO specification_body (id, content) VALUES ('838', '23 feb. 2009') ;
INSERT INTO specification_body (id, content) VALUES ('839', '22 jan. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('840', '15 may 2016') ;
INSERT INTO specification_body (id, content) VALUES ('841', '13 april 2015') ;
INSERT INTO specification_body (id, content) VALUES ('842', '27 april 2017') ;
INSERT INTO specification_body (id, content) VALUES ('843', '14 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('844', '23 july 2017') ;
INSERT INTO specification_body (id, content) VALUES ('845', '21 mar. 2014') ;
INSERT INTO specification_body (id, content) VALUES ('846', '9 nov. 1998') ;
INSERT INTO specification_body (id, content) VALUES ('847', '3 jan. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('848', '10 nov. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('849', '29 jun. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('850', '9 july 2013') ;
INSERT INTO specification_body (id, content) VALUES ('851', '18 aug. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('852', '6 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('853', '12 sept. 2011') ;
INSERT INTO specification_body (id, content) VALUES ('854', '20 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('855', '27 aug. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('856', '18 aug. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('857', '26 jan. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('858', '1 jan. 2012') ;
INSERT INTO specification_body (id, content) VALUES ('859', '25 july 2016') ;
INSERT INTO specification_body (id, content) VALUES ('860', '8 dec. 2011') ;
INSERT INTO specification_body (id, content) VALUES ('861', '10 april 2013') ;
INSERT INTO specification_body (id, content) VALUES ('862', '27 mar. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('863', '20 april 2015') ;
INSERT INTO specification_body (id, content) VALUES ('864', '6 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('865', '1 jan. 2010') ;
INSERT INTO specification_body (id, content) VALUES ('866', '2 sept. 2013') ;
INSERT INTO specification_body (id, content) VALUES ('867', '1 jan. 1900') ;
INSERT INTO specification_body (id, content) VALUES ('868', '1 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('869', '25 feb. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('870', '21 sept. 2010') ;
INSERT INTO specification_body (id, content) VALUES ('871', '8 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('872', '22 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('873', '16 mar. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('874', '23 mar. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('875', '3 jun. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('876', '15 jun. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('877', '26 jan. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('878', '16 mar. 2006') ;
INSERT INTO specification_body (id, content) VALUES ('879', '15 july 2016') ;
INSERT INTO specification_body (id, content) VALUES ('880', '15 sept. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('881', '22 aug. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('882', '20 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('883', '1 mar. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('884', '2 nov. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('885', '6 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('886', '18 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('887', '22 july 2015') ;
INSERT INTO specification_body (id, content) VALUES ('888', '21 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('889', '10 oct. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('890', '26 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('891', '9 april 2014') ;
INSERT INTO specification_body (id, content) VALUES ('892', '20 dec. 2001') ;
INSERT INTO specification_body (id, content) VALUES ('893', '22 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('894', '25 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('895', '9 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('896', '10 oct. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('897', '3 nov. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('898', '14 july 2018') ;
INSERT INTO specification_body (id, content) VALUES ('899', '15 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('900', '1 mar. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('901', '9 dec. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('902', '16 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('903', '9 nov. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('904', '10 feb. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('905', '31 aug. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('906', '1 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('907', '1 sept. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('908', '13 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('909', '13 nov. 2006') ;
INSERT INTO specification_body (id, content) VALUES ('910', '16 jun. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('911', '15 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('912', '12 nov. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('913', '17 july 2015') ;
INSERT INTO specification_body (id, content) VALUES ('914', '26 nov. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('915', '7 dec. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('916', '30 july 2015') ;
INSERT INTO specification_body (id, content) VALUES ('917', '2 mar. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('918', '24 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('919', '21 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('920', '9 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('921', '20 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('922', '6 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('923', '17 nov. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('924', '1 jun. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('925', '14 nov. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('926', '18 mar. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('927', '17 mar. 2006') ;
INSERT INTO specification_body (id, content) VALUES ('928', '24 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('929', '15 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('930', '2 jan. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('931', '11 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('932', '15 july 2011') ;
INSERT INTO specification_body (id, content) VALUES ('933', '23 july 2009') ;
INSERT INTO specification_body (id, content) VALUES ('934', '17 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('935', '17 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('936', '25 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('937', '18 nov. 2014') ;
INSERT INTO specification_body (id, content) VALUES ('938', '3 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('939', '20 feb. 2013') ;
INSERT INTO specification_body (id, content) VALUES ('940', '15 mar. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('941', '4 jun. 2010') ;
INSERT INTO specification_body (id, content) VALUES ('942', '2 mar. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('943', '20 aug. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('944', '13 dec. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('945', '5 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('946', '11 april 2017') ;
INSERT INTO specification_body (id, content) VALUES ('947', '24 jan. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('784', 'cd') ;
INSERT INTO specification_body (id, content) VALUES ('785', 'mini') ;
INSERT INTO specification_body (id, content) VALUES ('786', 'notebook') ;
INSERT INTO specification_body (id, content) VALUES ('787', 'laptop') ;
INSERT INTO specification_body (id, content) VALUES ('788', 'portable') ;
INSERT INTO specification_body (id, content) VALUES ('789', 'small form factor') ;
INSERT INTO specification_body (id, content) VALUES ('790', 'na') ;
INSERT INTO specification_body (id, content) VALUES ('791', 'tower') ;
INSERT INTO specification_body (id, content) VALUES ('792', 'standard') ;
INSERT INTO specification_body (id, content) VALUES ('793', 'cherry mx red') ;
INSERT INTO specification_body (id, content) VALUES ('794', 'black') ;
INSERT INTO specification_body (id, content) VALUES ('795', 'blue') ;
INSERT INTO specification_body (id, content) VALUES ('796', 'platinum grey') ;
INSERT INTO specification_body (id, content) VALUES ('797', 'silver') ;
INSERT INTO specification_body (id, content) VALUES ('798', 'grey') ;
INSERT INTO specification_body (id, content) VALUES ('799', 'blue/grey') ;
INSERT INTO specification_body (id, content) VALUES ('800', 'red') ;
INSERT INTO specification_body (id, content) VALUES ('801', 'aqua blue') ;
INSERT INTO specification_body (id, content) VALUES ('802', 'dark grey/white') ;
INSERT INTO specification_body (id, content) VALUES ('803', 'white') ;
INSERT INTO specification_body (id, content) VALUES ('804', 'chocolate black') ;
INSERT INTO specification_body (id, content) VALUES ('805', 'white and silver') ;
INSERT INTO specification_body (id, content) VALUES ('806', 'chroma v2') ;
INSERT INTO specification_body (id, content) VALUES ('807', 'violet purple') ;
INSERT INTO specification_body (id, content) VALUES ('808', 'cherry mx speed') ;
INSERT INTO specification_body (id, content) VALUES ('809', 'black & gold') ;
INSERT INTO specification_body (id, content) VALUES ('810', 'graphite') ;
INSERT INTO specification_body (id, content) VALUES ('811', 'huawei matebook d 14"') ;
INSERT INTO specification_body (id, content) VALUES ('812', 'platinum') ;
INSERT INTO specification_body (id, content) VALUES ('813', 'purple') ;
INSERT INTO specification_body (id, content) VALUES ('814', 'carbon') ;
INSERT INTO specification_body (id, content) VALUES ('815', 'matebook x pro 13.9"') ;
INSERT INTO specification_body (id, content) VALUES ('816', 'rtx 2060 / 240gb ssd / 2tb hdd') ;
INSERT INTO specification_body (id, content) VALUES ('817', 'black - g305') ;
INSERT INTO specification_body (id, content) VALUES ('948', 'true') ;
INSERT INTO specification_body (id, content) VALUES ('949', 'false') ;
