INSERT INTO specification_body (id, content) VALUES ('350', '1') ;
INSERT INTO specification_body (id, content) VALUES ('351', '2') ;
INSERT INTO specification_body (id, content) VALUES ('352', '3') ;
INSERT INTO specification_body (id, content) VALUES ('353', '4') ;
INSERT INTO specification_body (id, content) VALUES ('119', '21949') ;
INSERT INTO specification_body (id, content) VALUES ('120', '74940') ;
INSERT INTO specification_body (id, content) VALUES ('131', '75002') ;
INSERT INTO specification_body (id, content) VALUES ('124', '713368') ;
INSERT INTO specification_body (id, content) VALUES ('76', '765489') ;
INSERT INTO specification_body (id, content) VALUES ('123', '842949') ;
INSERT INTO specification_body (id, content) VALUES ('121', '848361') ;
INSERT INTO specification_body (id, content) VALUES ('0', '1.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('1', '90.7 g') ;
INSERT INTO specification_body (id, content) VALUES ('2', '599 g') ;
INSERT INTO specification_body (id, content) VALUES ('3', '259 g') ;
INSERT INTO specification_body (id, content) VALUES ('4', '9.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('5', '59 g') ;
INSERT INTO specification_body (id, content) VALUES ('6', '16.4 kg') ;
INSERT INTO specification_body (id, content) VALUES ('7', '159 g') ;
INSERT INTO specification_body (id, content) VALUES ('8', '522 g') ;
INSERT INTO specification_body (id, content) VALUES ('9', '281 g') ;
INSERT INTO specification_body (id, content) VALUES ('10', '2.6 kg') ;
INSERT INTO specification_body (id, content) VALUES ('11', '2.4 kg') ;
INSERT INTO specification_body (id, content) VALUES ('12', '780 g') ;
INSERT INTO specification_body (id, content) VALUES ('13', '81.6 g') ;
INSERT INTO specification_body (id, content) VALUES ('14', '12.2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('15', '621 g') ;
INSERT INTO specification_body (id, content) VALUES ('16', '8.4 kg') ;
INSERT INTO specification_body (id, content) VALUES ('17', '2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('18', '10.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('19', '68 g') ;
INSERT INTO specification_body (id, content) VALUES ('20', '2.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('21', '1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('22', '989 g') ;
INSERT INTO specification_body (id, content) VALUES ('23', '322 g') ;
INSERT INTO specification_body (id, content) VALUES ('24', '240 g') ;
INSERT INTO specification_body (id, content) VALUES ('25', '181 g') ;
INSERT INTO specification_body (id, content) VALUES ('26', '118 g') ;
INSERT INTO specification_body (id, content) VALUES ('27', '2.3 kg') ;
INSERT INTO specification_body (id, content) VALUES ('28', '1.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('29', '331 g') ;
INSERT INTO specification_body (id, content) VALUES ('30', '458 g') ;
INSERT INTO specification_body (id, content) VALUES ('31', '3 kg') ;
INSERT INTO specification_body (id, content) VALUES ('32', '200 g') ;
INSERT INTO specification_body (id, content) VALUES ('33', '998 g') ;
INSERT INTO specification_body (id, content) VALUES ('34', '499 g') ;
INSERT INTO specification_body (id, content) VALUES ('35', '40.8 g') ;
INSERT INTO specification_body (id, content) VALUES ('36', '5.5 kg') ;
INSERT INTO specification_body (id, content) VALUES ('37', '2.2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('38', '340 g') ;
INSERT INTO specification_body (id, content) VALUES ('39', '676 g') ;
INSERT INTO specification_body (id, content) VALUES ('40', '7 kg') ;
INSERT INTO specification_body (id, content) VALUES ('41', '662 g') ;
INSERT INTO specification_body (id, content) VALUES ('42', '16.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('43', '18.1 g') ;
INSERT INTO specification_body (id, content) VALUES ('44', '10 kg') ;
INSERT INTO specification_body (id, content) VALUES ('45', '6.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('46', '540 g') ;
INSERT INTO specification_body (id, content) VALUES ('47', '1.6 kg') ;
INSERT INTO specification_body (id, content) VALUES ('48', '3.2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('49', '299 g') ;
INSERT INTO specification_body (id, content) VALUES ('50', '31.8 g') ;
INSERT INTO specification_body (id, content) VALUES ('51', '381 g') ;
INSERT INTO specification_body (id, content) VALUES ('52', '141 g') ;
INSERT INTO specification_body (id, content) VALUES ('53', '581 g') ;
INSERT INTO specification_body (id, content) VALUES ('54', '558 g') ;
INSERT INTO specification_body (id, content) VALUES ('55', '748 g') ;
INSERT INTO specification_body (id, content) VALUES ('56', '7.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('57', '7.9 kg') ;
INSERT INTO specification_body (id, content) VALUES ('58', '2.5 kg') ;
INSERT INTO specification_body (id, content) VALUES ('59', '762 g') ;
INSERT INTO specification_body (id, content) VALUES ('60', '449 g') ;
INSERT INTO specification_body (id, content) VALUES ('61', '862 g') ;
INSERT INTO specification_body (id, content) VALUES ('62', '6.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('63', '327 g') ;
INSERT INTO specification_body (id, content) VALUES ('64', '2.9 kg') ;
INSERT INTO specification_body (id, content) VALUES ('65', '1.9 kg') ;
INSERT INTO specification_body (id, content) VALUES ('66', '1.7 kg') ;
INSERT INTO specification_body (id, content) VALUES ('67', '15 kg') ;
INSERT INTO specification_body (id, content) VALUES ('68', '49.9 g') ;
INSERT INTO specification_body (id, content) VALUES ('69', '776 g') ;
INSERT INTO specification_body (id, content) VALUES ('70', '721 g') ;
INSERT INTO specification_body (id, content) VALUES ('71', 'ch-9109010-uk') ;
INSERT INTO specification_body (id, content) VALUES ('72', 'ca57bn-ukvv1') ;
INSERT INTO specification_body (id, content) VALUES ('73', 'pro-002') ;
INSERT INTO specification_body (id, content) VALUES ('74', '.') ;
INSERT INTO specification_body (id, content) VALUES ('75', 'pagepc079ab-ukaa1') ;
INSERT INTO specification_body (id, content) VALUES ('77', 'k380') ;
INSERT INTO specification_body (id, content) VALUES ('78', '80xl03s8uk') ;
INSERT INTO specification_body (id, content) VALUES ('79', '4ew09ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('80', '910-002225') ;
INSERT INTO specification_body (id, content) VALUES ('81', 'bt3pro') ;
INSERT INTO specification_body (id, content) VALUES ('82', 'slimkeyproa-uk') ;
INSERT INTO specification_body (id, content) VALUES ('83', 'e201na-gj008t-oss') ;
INSERT INTO specification_body (id, content) VALUES ('84', 'anb-00006') ;
INSERT INTO specification_body (id, content) VALUES ('85', 'pro-001') ;
INSERT INTO specification_body (id, content) VALUES ('86', '14-ax005na') ;
INSERT INTO specification_body (id, content) VALUES ('87', '3rn80ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('88', '920-008041') ;
INSERT INTO specification_body (id, content) VALUES ('89', '2458x00140') ;
INSERT INTO specification_body (id, content) VALUES ('90', '2cs90ea') ;
INSERT INTO specification_body (id, content) VALUES ('91', 'x540na-gq232t') ;
INSERT INTO specification_body (id, content) VALUES ('92', 'acepc t8') ;
INSERT INTO specification_body (id, content) VALUES ('93', 'rock0813') ;
INSERT INTO specification_body (id, content) VALUES ('94', '910-003357') ;
INSERT INTO specification_body (id, content) VALUES ('95', 'nx.gc2ek.007') ;
INSERT INTO specification_body (id, content) VALUES ('96', 'signature pro') ;
INSERT INTO specification_body (id, content) VALUES ('97', 'aud athad500x') ;
INSERT INTO specification_body (id, content) VALUES ('98', 'xf8rm') ;
INSERT INTO specification_body (id, content) VALUES ('99', 'm7j-00020') ;
INSERT INTO specification_body (id, content) VALUES ('100', 'thinkpad t430') ;
INSERT INTO specification_body (id, content) VALUES ('101', '910-001882') ;
INSERT INTO specification_body (id, content) VALUES ('102', 'aud athe40') ;
INSERT INTO specification_body (id, content) VALUES ('103', 'ath-avc200') ;
INSERT INTO specification_body (id, content) VALUES ('104', 'oe-ca-11re') ;
INSERT INTO specification_body (id, content) VALUES ('105', 'rz03-02030400-r3w1') ;
INSERT INTO specification_body (id, content) VALUES ('106', 'hpx2000') ;
INSERT INTO specification_body (id, content) VALUES ('107', 'mini i8bt mini bluetooth keyboard') ;
INSERT INTO specification_body (id, content) VALUES ('108', '2470x00190') ;
INSERT INTO specification_body (id, content) VALUES ('109', '3rn81ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('110', '2058x00190') ;
INSERT INTO specification_body (id, content) VALUES ('111', 'ms-scroller') ;
INSERT INTO specification_body (id, content) VALUES ('112', 'nx.gc2ek.003') ;
INSERT INTO specification_body (id, content) VALUES ('113', 'e203ma-fd001ts') ;
INSERT INTO specification_body (id, content) VALUES ('114', '4yr34') ;
INSERT INTO specification_body (id, content) VALUES ('115', '910-005313') ;
INSERT INTO specification_body (id, content) VALUES ('116', 'jh-811') ;
INSERT INTO specification_body (id, content) VALUES ('117', 'ch-9109014-uk') ;
INSERT INTO specification_body (id, content) VALUES ('118', '920-008503') ;
INSERT INTO specification_body (id, content) VALUES ('122', 'chromebit-b004c') ;
INSERT INTO specification_body (id, content) VALUES ('125', 'i8+bt mini wireless bluetooth keyboard') ;
INSERT INTO specification_body (id, content) VALUES ('126', 'k92') ;
INSERT INTO specification_body (id, content) VALUES ('127', 'ath-anc700btbk') ;
INSERT INTO specification_body (id, content) VALUES ('128', 'cp003473') ;
INSERT INTO specification_body (id, content) VALUES ('129', '910-005139') ;
INSERT INTO specification_body (id, content) VALUES ('130', '53010fhs') ;
INSERT INTO specification_body (id, content) VALUES ('132', 'rp-dj1200e-k') ;
INSERT INTO specification_body (id, content) VALUES ('133', 'dap-00009') ;
INSERT INTO specification_body (id, content) VALUES ('134', 'm185') ;
INSERT INTO specification_body (id, content) VALUES ('135', 'srh840') ;
INSERT INTO specification_body (id, content) VALUES ('136', 't90b+ pro') ;
INSERT INTO specification_body (id, content) VALUES ('137', 'c423na-bv0078') ;
INSERT INTO specification_body (id, content) VALUES ('138', 'hf150') ;
INSERT INTO specification_body (id, content) VALUES ('139', 'nx.g54ek.005') ;
INSERT INTO specification_body (id, content) VALUES ('140', 'fba_920-003745') ;
INSERT INTO specification_body (id, content) VALUES ('141', 'ak-98anwvm-uba') ;
INSERT INTO specification_body (id, content) VALUES ('142', '920-008867') ;
INSERT INTO specification_body (id, content) VALUES ('143', 'fba_920-002501') ;
INSERT INTO specification_body (id, content) VALUES ('144', 'mach-w29') ;
INSERT INTO specification_body (id, content) VALUES ('145', 'tscoazfba001') ;
INSERT INTO specification_body (id, content) VALUES ('146', '3rn89ea#abu') ;
INSERT INTO specification_body (id, content) VALUES ('147', 'ad-39e-790-1070-850-w10') ;
INSERT INTO specification_body (id, content) VALUES ('148', 'c302ca-gu010') ;
INSERT INTO specification_body (id, content) VALUES ('149', 'vt-0412-lm') ;
INSERT INTO specification_body (id, content) VALUES ('150', '81bg00c8uk') ;
INSERT INTO specification_body (id, content) VALUES ('151', '910-005283') ;
INSERT INTO specification_body (id, content) VALUES ('152', 'e5athr70x') ;
INSERT INTO specification_body (id, content) VALUES ('153', 'hpx4000') ;
INSERT INTO specification_body (id, content) VALUES ('154', 'corsair') ;
INSERT INTO specification_body (id, content) VALUES ('155', 'patuoxun') ;
INSERT INTO specification_body (id, content) VALUES ('156', 'oneodio') ;
INSERT INTO specification_body (id, content) VALUES ('157', 'limson') ;
INSERT INTO specification_body (id, content) VALUES ('158', 'admi') ;
INSERT INTO specification_body (id, content) VALUES ('159', 'the stone roses') ;
INSERT INTO specification_body (id, content) VALUES ('160', 'dell') ;
INSERT INTO specification_body (id, content) VALUES ('161', 'drymartine') ;
INSERT INTO specification_body (id, content) VALUES ('162', 'logitech') ;
INSERT INTO specification_body (id, content) VALUES ('163', 'emopeak') ;
INSERT INTO specification_body (id, content) VALUES ('164', 'lenovo') ;
INSERT INTO specification_body (id, content) VALUES ('165', 'hp') ;
INSERT INTO specification_body (id, content) VALUES ('166', 'yuancin') ;
INSERT INTO specification_body (id, content) VALUES ('167', 'macally') ;
INSERT INTO specification_body (id, content) VALUES ('168', 'kz') ;
INSERT INTO specification_body (id, content) VALUES ('169', 'the small faces') ;
INSERT INTO specification_body (id, content) VALUES ('170', 'asus') ;
INSERT INTO specification_body (id, content) VALUES ('171', 'microsoft') ;
INSERT INTO specification_body (id, content) VALUES ('172', 'paul simon') ;
INSERT INTO specification_body (id, content) VALUES ('173', 'jungle') ;
INSERT INTO specification_body (id, content) VALUES ('174', 'duran duran') ;
INSERT INTO specification_body (id, content) VALUES ('175', 'alangduo') ;
INSERT INTO specification_body (id, content) VALUES ('176', 'r.e.m.') ;
INSERT INTO specification_body (id, content) VALUES ('177', 'akg') ;
INSERT INTO specification_body (id, content) VALUES ('178', 'bestoppen women lingerie') ;
INSERT INTO specification_body (id, content) VALUES ('179', 'ed sheeran') ;
INSERT INTO specification_body (id, content) VALUES ('180', 'various artists') ;
INSERT INTO specification_body (id, content) VALUES ('181', 'acepc') ;
INSERT INTO specification_body (id, content) VALUES ('182', 'rockpapa') ;
INSERT INTO specification_body (id, content) VALUES ('183', 'khanka') ;
INSERT INTO specification_body (id, content) VALUES ('184', 'acer') ;
INSERT INTO specification_body (id, content) VALUES ('185', 'ultrasone') ;
INSERT INTO specification_body (id, content) VALUES ('186', 'audio-technica') ;
INSERT INTO specification_body (id, content) VALUES ('187', 'jelly comb') ;
INSERT INTO specification_body (id, content) VALUES ('188', 'frank sinatra') ;
INSERT INTO specification_body (id, content) VALUES ('189', 'the 1975') ;
INSERT INTO specification_body (id, content) VALUES ('190', 'the prodigy') ;
INSERT INTO specification_body (id, content) VALUES ('191', 'roger daltrey') ;
INSERT INTO specification_body (id, content) VALUES ('192', 'the beach boys') ;
INSERT INTO specification_body (id, content) VALUES ('193', 'audio technica') ;
INSERT INTO specification_body (id, content) VALUES ('194', 'cospor') ;
INSERT INTO specification_body (id, content) VALUES ('195', 'empire gaming') ;
INSERT INTO specification_body (id, content) VALUES ('196', 'razer') ;
INSERT INTO specification_body (id, content) VALUES ('197', 'behringer') ;
INSERT INTO specification_body (id, content) VALUES ('198', 'rii') ;
INSERT INTO specification_body (id, content) VALUES ('199', 'foo fighters') ;
INSERT INTO specification_body (id, content) VALUES ('200', 'fkant') ;
INSERT INTO specification_body (id, content) VALUES ('201', 'barbra streisand') ;
INSERT INTO specification_body (id, content) VALUES ('202', 'nashville cast') ;
INSERT INTO specification_body (id, content) VALUES ('203', 'james blake') ;
INSERT INTO specification_body (id, content) VALUES ('204', 'bestytt') ;
INSERT INTO specification_body (id, content) VALUES ('205', 'perixx') ;
INSERT INTO specification_body (id, content) VALUES ('206', 'apple') ;
INSERT INTO specification_body (id, content) VALUES ('207', 'cit') ;
INSERT INTO specification_body (id, content) VALUES ('208', 'bts') ;
INSERT INTO specification_body (id, content) VALUES ('209', 'gary clark jr.') ;
INSERT INTO specification_body (id, content) VALUES ('210', 'victsing') ;
INSERT INTO specification_body (id, content) VALUES ('211', 'in flames') ;
INSERT INTO specification_body (id, content) VALUES ('212', 'jiuhufh') ;
INSERT INTO specification_body (id, content) VALUES ('213', 'aokey') ;
INSERT INTO specification_body (id, content) VALUES ('214', 'ichoose limited') ;
INSERT INTO specification_body (id, content) VALUES ('215', 'busted') ;
INSERT INTO specification_body (id, content) VALUES ('216', 'trust') ;
INSERT INTO specification_body (id, content) VALUES ('217', 'george michael') ;
INSERT INTO specification_body (id, content) VALUES ('218', 'avantasia') ;
INSERT INTO specification_body (id, content) VALUES ('219', 'richard thompson') ;
INSERT INTO specification_body (id, content) VALUES ('220', 'tecknet') ;
INSERT INTO specification_body (id, content) VALUES ('221', 'coldplay') ;
INSERT INTO specification_body (id, content) VALUES ('222', 'beyerdynamic') ;
INSERT INTO specification_body (id, content) VALUES ('223', 'billy f gibbons') ;
INSERT INTO specification_body (id, content) VALUES ('224', 'bestfy') ;
INSERT INTO specification_body (id, content) VALUES ('225', 'kylie minogue') ;
INSERT INTO specification_body (id, content) VALUES ('226', 'take that') ;
INSERT INTO specification_body (id, content) VALUES ('227', 'huawei') ;
INSERT INTO specification_body (id, content) VALUES ('228', 'aiaiai') ;
INSERT INTO specification_body (id, content) VALUES ('229', 'panasonic') ;
INSERT INTO specification_body (id, content) VALUES ('230', 'christina aguilera') ;
INSERT INTO specification_body (id, content) VALUES ('231', 'hunpta') ;
INSERT INTO specification_body (id, content) VALUES ('232', 'arctic monkeys') ;
INSERT INTO specification_body (id, content) VALUES ('233', 'shure') ;
INSERT INTO specification_body (id, content) VALUES ('234', 'fusion5') ;
INSERT INTO specification_body (id, content) VALUES ('235', 'weezer') ;
INSERT INTO specification_body (id, content) VALUES ('236', 'numark') ;
INSERT INTO specification_body (id, content) VALUES ('237', 'dream theater') ;
INSERT INTO specification_body (id, content) VALUES ('238', 'anker') ;
INSERT INTO specification_body (id, content) VALUES ('239', 'the shires') ;
INSERT INTO specification_body (id, content) VALUES ('240', 'kidz bop kids') ;
INSERT INTO specification_body (id, content) VALUES ('241', 'tscoaz') ;
INSERT INTO specification_body (id, content) VALUES ('242', 'pentium') ;
INSERT INTO specification_body (id, content) VALUES ('243', 'core 2 quad') ;
INSERT INTO specification_body (id, content) VALUES ('244', 'core i5') ;
INSERT INTO specification_body (id, content) VALUES ('245', 'atom') ;
INSERT INTO specification_body (id, content) VALUES ('246', 'a series') ;
INSERT INTO specification_body (id, content) VALUES ('247', 'celeron') ;
INSERT INTO specification_body (id, content) VALUES ('248', 'r series') ;
INSERT INTO specification_body (id, content) VALUES ('249', 'core 2 duo') ;
INSERT INTO specification_body (id, content) VALUES ('250', 'core i3') ;
INSERT INTO specification_body (id, content) VALUES ('251', 'celeron n3350') ;
INSERT INTO specification_body (id, content) VALUES ('252', 'core i7') ;
INSERT INTO specification_body (id, content) VALUES ('253', 'core i7 8550u') ;
INSERT INTO specification_body (id, content) VALUES ('254', 'none') ;
INSERT INTO specification_body (id, content) VALUES ('271', 'intel') ;
INSERT INTO specification_body (id, content) VALUES ('277', 'amd') ;
INSERT INTO specification_body (id, content) VALUES ('257', 'amd®') ;
INSERT INTO specification_body (id, content) VALUES ('258', 'rockchip') ;
INSERT INTO specification_body (id, content) VALUES ('259', 'intel®') ;
INSERT INTO specification_body (id, content) VALUES ('263', 'nvidia geforce gtx 1050 ti') ;
INSERT INTO specification_body (id, content) VALUES ('264', 'uhd graphics') ;
INSERT INTO specification_body (id, content) VALUES ('265', 'amd radeon r4') ;
INSERT INTO specification_body (id, content) VALUES ('266', 'amd rx 570 4gb') ;
INSERT INTO specification_body (id, content) VALUES ('267', 'integrated') ;
INSERT INTO specification_body (id, content) VALUES ('268', 'hd graphics') ;
INSERT INTO specification_body (id, content) VALUES ('269', 'nvidia geforce gtx 900') ;
INSERT INTO specification_body (id, content) VALUES ('270', 'intel hd graphics') ;
INSERT INTO specification_body (id, content) VALUES ('272', 'intel hd graphics 4000') ;
INSERT INTO specification_body (id, content) VALUES ('273', 'intel hd graphics 4400') ;
INSERT INTO specification_body (id, content) VALUES ('274', 'intel hd graphics 2500') ;
INSERT INTO specification_body (id, content) VALUES ('275', 'integrated/on-board graphics') ;
INSERT INTO specification_body (id, content) VALUES ('276', 'intel gma 4500hd') ;
INSERT INTO specification_body (id, content) VALUES ('278', 'intel hd graphics 5300') ;
INSERT INTO specification_body (id, content) VALUES ('279', 'intel hd graphics 500') ;
INSERT INTO specification_body (id, content) VALUES ('280', 'intel hd graphics 610') ;
INSERT INTO specification_body (id, content) VALUES ('281', 'nvidia geforce mx150') ;
INSERT INTO specification_body (id, content) VALUES ('282', 'nvidia rtx 2060 6gb') ;
INSERT INTO specification_body (id, content) VALUES ('283', 'intel uhd graphics 620') ;
INSERT INTO specification_body (id, content) VALUES ('284', '1 tb') ;
INSERT INTO specification_body (id, content) VALUES ('285', '160 gb') ;
INSERT INTO specification_body (id, content) VALUES ('286', '2 tb') ;
INSERT INTO specification_body (id, content) VALUES ('287', '256 gb') ;
INSERT INTO specification_body (id, content) VALUES ('288', '64 gb') ;
INSERT INTO specification_body (id, content) VALUES ('289', '32 gb') ;
INSERT INTO specification_body (id, content) VALUES ('290', '1000 gb') ;
INSERT INTO specification_body (id, content) VALUES ('308', '16 gb') ;
INSERT INTO specification_body (id, content) VALUES ('292', '1024 gb') ;
INSERT INTO specification_body (id, content) VALUES ('293', '128 gb') ;
INSERT INTO specification_body (id, content) VALUES ('294', '512 gb') ;
INSERT INTO specification_body (id, content) VALUES ('295', '240 gb') ;
INSERT INTO specification_body (id, content) VALUES ('296', 'hdd 7200 rpm') ;
INSERT INTO specification_body (id, content) VALUES ('297', 'hdd') ;
INSERT INTO specification_body (id, content) VALUES ('298', 'sdd') ;
INSERT INTO specification_body (id, content) VALUES ('299', 'emmc') ;
INSERT INTO specification_body (id, content) VALUES ('300', 'ssd') ;
INSERT INTO specification_body (id, content) VALUES ('301', 'ssd, hdd') ;
INSERT INTO specification_body (id, content) VALUES ('302', 'sata') ;
INSERT INTO specification_body (id, content) VALUES ('303', 'mechanical hard drive') ;
INSERT INTO specification_body (id, content) VALUES ('304', '8 gb') ;
INSERT INTO specification_body (id, content) VALUES ('305', '4 gb') ;
INSERT INTO specification_body (id, content) VALUES ('306', '8192 mb') ;
INSERT INTO specification_body (id, content) VALUES ('307', '2 gb') ;
INSERT INTO specification_body (id, content) VALUES ('309', 'compatible with most systems including windows 7 / 8 / 10 / xp, vista 7 / 8, mac and linux. note: side buttons are invalid in mac os') ;
INSERT INTO specification_body (id, content) VALUES ('310', 'windows 10 home') ;
INSERT INTO specification_body (id, content) VALUES ('311', 'windows 10 professional + office pro full version') ;
INSERT INTO specification_body (id, content) VALUES ('312', 'windows 10') ;
INSERT INTO specification_body (id, content) VALUES ('313', 'windows 10/windows 8/windows 8.1/windows 7/windows rt 8.1/windows rt 8') ;
INSERT INTO specification_body (id, content) VALUES ('314', 'windows 10 professional') ;
INSERT INTO specification_body (id, content) VALUES ('315', 'windows 10 pro') ;
INSERT INTO specification_body (id, content) VALUES ('316', 'microsoft windows xp, windows vista, windows 7, linux 2.4 +, mac os x 10.3.9 +') ;
INSERT INTO specification_body (id, content) VALUES ('317', 'chrome os') ;
INSERT INTO specification_body (id, content) VALUES ('318', 'win xp, vista, 7^mac 10.5 +') ;
INSERT INTO specification_body (id, content) VALUES ('319', 'os x el capitan') ;
INSERT INTO specification_body (id, content) VALUES ('320', 'windows xp, vista, 7^mac os x 10.5+^linux kernel 2.6+') ;
INSERT INTO specification_body (id, content) VALUES ('321', 'windows xp/vista/7^linux 2.6+') ;
INSERT INTO specification_body (id, content) VALUES ('322', '15 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('323', '15.6 inches') ;
INSERT INTO specification_body (id, content) VALUES ('324', '33.8 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('325', '29 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('326', '35.6 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('327', '14 inches') ;
INSERT INTO specification_body (id, content) VALUES ('328', '39.624 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('329', '11.6 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('330', '14.10 inches') ;
INSERT INTO specification_body (id, content) VALUES ('331', '20 inches') ;
INSERT INTO specification_body (id, content) VALUES ('332', '35.56 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('333', '29.46 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('334', '39.62 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('335', '34.29 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('336', '35.3 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('337', '11.6 inches') ;
INSERT INTO specification_body (id, content) VALUES ('338', '31.75 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('339', '39.6 centimetres') ;
INSERT INTO specification_body (id, content) VALUES ('340', '1366 x 768 pixels') ;
INSERT INTO specification_body (id, content) VALUES ('341', '1920 x 1080') ;
INSERT INTO specification_body (id, content) VALUES ('342', '1366 x 768') ;
INSERT INTO specification_body (id, content) VALUES ('343', '1920x1080') ;
INSERT INTO specification_body (id, content) VALUES ('344', '1600x900') ;
INSERT INTO specification_body (id, content) VALUES ('345', '1366x768') ;
INSERT INTO specification_body (id, content) VALUES ('346', '1920 x 1080 pixels') ;
INSERT INTO specification_body (id, content) VALUES ('347', '2256 x 1504') ;
INSERT INTO specification_body (id, content) VALUES ('348', '3840 x 2160') ;
INSERT INTO specification_body (id, content) VALUES ('349', '3000 x 2000 pixels') ;
INSERT INTO specification_body (id, content) VALUES ('354', 'sony music cmg') ;
INSERT INTO specification_body (id, content) VALUES ('355', 'castle communications') ;
INSERT INTO specification_body (id, content) VALUES ('356', 'xl recordings') ;
INSERT INTO specification_body (id, content) VALUES ('357', 'emi') ;
INSERT INTO specification_body (id, content) VALUES ('358', 'umc') ;
INSERT INTO specification_body (id, content) VALUES ('359', 'atlantic') ;
INSERT INTO specification_body (id, content) VALUES ('360', 'decca umo') ;
INSERT INTO specification_body (id, content) VALUES ('361', 'universal') ;
INSERT INTO specification_body (id, content) VALUES ('362', 'xl') ;
INSERT INTO specification_body (id, content) VALUES ('363', 'polydor') ;
INSERT INTO specification_body (id, content) VALUES ('364', 'now') ;
INSERT INTO specification_body (id, content) VALUES ('365', 'sony music') ;
INSERT INTO specification_body (id, content) VALUES ('366', 'sony commercial group') ;
INSERT INTO specification_body (id, content) VALUES ('367', 'umo') ;
INSERT INTO specification_body (id, content) VALUES ('368', 'import') ;
INSERT INTO specification_body (id, content) VALUES ('369', 'warner bros') ;
INSERT INTO specification_body (id, content) VALUES ('370', 'umod') ;
INSERT INTO specification_body (id, content) VALUES ('371', 'nuclear blast') ;
INSERT INTO specification_body (id, content) VALUES ('372', 'busted lp2') ;
INSERT INTO specification_body (id, content) VALUES ('373', 'sonybmg') ;
INSERT INTO specification_body (id, content) VALUES ('374', 'proper records') ;
INSERT INTO specification_body (id, content) VALUES ('375', 'plg uk frontline') ;
INSERT INTO specification_body (id, content) VALUES ('376', 'snakefarm records') ;
INSERT INTO specification_body (id, content) VALUES ('377', 'bmg rights management uk ltd') ;
INSERT INTO specification_body (id, content) VALUES ('378', 'trojan records') ;
INSERT INTO specification_body (id, content) VALUES ('379', 'rca') ;
INSERT INTO specification_body (id, content) VALUES ('380', 'domino') ;
INSERT INTO specification_body (id, content) VALUES ('381', 'insideoutmusic') ;
INSERT INTO specification_body (id, content) VALUES ('382', 'decca others') ;
INSERT INTO specification_body (id, content) VALUES ('383', 'concord records') ;
INSERT INTO specification_body (id, content) VALUES ('810', '12 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('811', '18 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('812', '4 feb. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('813', '2 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('814', '10 may 2017') ;
INSERT INTO specification_body (id, content) VALUES ('815', '14 april 2014') ;
INSERT INTO specification_body (id, content) VALUES ('816', '17 aug. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('817', '25 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('818', '16 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('819', '3 sept. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('820', '27 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('821', '15 dec. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('822', '21 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('823', '25 jun. 2011') ;
INSERT INTO specification_body (id, content) VALUES ('824', '31 july 2017') ;
INSERT INTO specification_body (id, content) VALUES ('825', '9 aug. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('826', '8 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('827', '14 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('828', '3 mar. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('829', '23 may 2017') ;
INSERT INTO specification_body (id, content) VALUES ('830', '23 feb. 2009') ;
INSERT INTO specification_body (id, content) VALUES ('831', '22 jan. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('832', '15 may 2016') ;
INSERT INTO specification_body (id, content) VALUES ('833', '13 april 2015') ;
INSERT INTO specification_body (id, content) VALUES ('834', '27 april 2017') ;
INSERT INTO specification_body (id, content) VALUES ('835', '14 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('836', '23 july 2017') ;
INSERT INTO specification_body (id, content) VALUES ('837', '21 mar. 2014') ;
INSERT INTO specification_body (id, content) VALUES ('838', '9 nov. 1998') ;
INSERT INTO specification_body (id, content) VALUES ('839', '3 jan. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('840', '10 nov. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('841', '29 jun. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('842', '9 july 2013') ;
INSERT INTO specification_body (id, content) VALUES ('843', '18 aug. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('844', '25 mar. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('845', '6 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('846', '12 sept. 2011') ;
INSERT INTO specification_body (id, content) VALUES ('847', '20 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('848', '27 aug. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('849', '18 aug. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('850', '26 jan. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('851', '1 jan. 2012') ;
INSERT INTO specification_body (id, content) VALUES ('852', '25 july 2016') ;
INSERT INTO specification_body (id, content) VALUES ('853', '8 dec. 2011') ;
INSERT INTO specification_body (id, content) VALUES ('854', '10 april 2013') ;
INSERT INTO specification_body (id, content) VALUES ('855', '27 mar. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('856', '20 april 2015') ;
INSERT INTO specification_body (id, content) VALUES ('857', '6 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('858', '1 jan. 2010') ;
INSERT INTO specification_body (id, content) VALUES ('859', '2 sept. 2013') ;
INSERT INTO specification_body (id, content) VALUES ('860', '1 jan. 1900') ;
INSERT INTO specification_body (id, content) VALUES ('861', '1 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('862', '25 feb. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('863', '21 sept. 2010') ;
INSERT INTO specification_body (id, content) VALUES ('864', '8 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('865', '22 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('866', '16 mar. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('867', '23 mar. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('868', '3 jun. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('869', '15 jun. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('870', '26 jan. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('871', '16 mar. 2006') ;
INSERT INTO specification_body (id, content) VALUES ('872', '15 july 2016') ;
INSERT INTO specification_body (id, content) VALUES ('873', '15 sept. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('874', '22 aug. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('875', '20 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('876', '1 mar. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('877', '2 nov. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('878', '6 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('879', '18 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('880', '22 july 2015') ;
INSERT INTO specification_body (id, content) VALUES ('881', '21 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('882', '10 oct. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('883', '26 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('884', '9 april 2014') ;
INSERT INTO specification_body (id, content) VALUES ('885', '20 dec. 2001') ;
INSERT INTO specification_body (id, content) VALUES ('886', '22 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('887', '25 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('888', '9 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('889', '10 oct. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('890', '3 nov. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('891', '14 july 2018') ;
INSERT INTO specification_body (id, content) VALUES ('892', '15 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('893', '1 mar. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('894', '9 dec. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('895', '16 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('896', '9 nov. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('897', '10 feb. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('898', '31 aug. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('899', '1 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('900', '1 sept. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('901', '13 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('902', '13 nov. 2006') ;
INSERT INTO specification_body (id, content) VALUES ('903', '16 jun. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('904', '15 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('905', '12 nov. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('906', '17 july 2015') ;
INSERT INTO specification_body (id, content) VALUES ('907', '26 nov. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('908', '7 dec. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('909', '30 july 2015') ;
INSERT INTO specification_body (id, content) VALUES ('910', '2 mar. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('911', '24 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('912', '21 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('913', '9 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('914', '20 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('915', '6 april 2018') ;
INSERT INTO specification_body (id, content) VALUES ('916', '17 nov. 2008') ;
INSERT INTO specification_body (id, content) VALUES ('917', '1 jun. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('918', '14 nov. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('919', '18 mar. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('920', '17 mar. 2006') ;
INSERT INTO specification_body (id, content) VALUES ('921', '24 sept. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('922', '15 jun. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('923', '2 jan. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('924', '11 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('925', '15 july 2011') ;
INSERT INTO specification_body (id, content) VALUES ('926', '23 july 2009') ;
INSERT INTO specification_body (id, content) VALUES ('927', '17 may 2018') ;
INSERT INTO specification_body (id, content) VALUES ('928', '17 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('929', '25 feb. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('930', '18 nov. 2014') ;
INSERT INTO specification_body (id, content) VALUES ('931', '3 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('932', '20 feb. 2013') ;
INSERT INTO specification_body (id, content) VALUES ('933', '15 mar. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('934', '4 jun. 2010') ;
INSERT INTO specification_body (id, content) VALUES ('935', '2 mar. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('936', '20 aug. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('937', '13 dec. 2018') ;
INSERT INTO specification_body (id, content) VALUES ('938', '5 jan. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('939', '11 april 2017') ;
INSERT INTO specification_body (id, content) VALUES ('940', '24 jan. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('777', 'mini') ;
INSERT INTO specification_body (id, content) VALUES ('778', 'notebook') ;
INSERT INTO specification_body (id, content) VALUES ('779', 'laptop') ;
INSERT INTO specification_body (id, content) VALUES ('780', 'small form factor') ;
INSERT INTO specification_body (id, content) VALUES ('781', 'portable') ;
INSERT INTO specification_body (id, content) VALUES ('782', 'na') ;
INSERT INTO specification_body (id, content) VALUES ('783', 'tower') ;
INSERT INTO specification_body (id, content) VALUES ('784', 'standard') ;
INSERT INTO specification_body (id, content) VALUES ('785', 'cherry mx red') ;
INSERT INTO specification_body (id, content) VALUES ('786', 'black') ;
INSERT INTO specification_body (id, content) VALUES ('787', 'blue') ;
INSERT INTO specification_body (id, content) VALUES ('788', 'platinum grey') ;
INSERT INTO specification_body (id, content) VALUES ('789', 'silver') ;
INSERT INTO specification_body (id, content) VALUES ('790', 'grey') ;
INSERT INTO specification_body (id, content) VALUES ('791', 'blue/grey') ;
INSERT INTO specification_body (id, content) VALUES ('792', 'red') ;
INSERT INTO specification_body (id, content) VALUES ('793', 'aqua blue') ;
INSERT INTO specification_body (id, content) VALUES ('794', 'dark grey/white') ;
INSERT INTO specification_body (id, content) VALUES ('795', 'white') ;
INSERT INTO specification_body (id, content) VALUES ('796', 'chocolate black') ;
INSERT INTO specification_body (id, content) VALUES ('797', 'white and silver') ;
INSERT INTO specification_body (id, content) VALUES ('798', 'chroma v2') ;
INSERT INTO specification_body (id, content) VALUES ('799', 'violet purple') ;
INSERT INTO specification_body (id, content) VALUES ('800', 'cherry mx speed') ;
INSERT INTO specification_body (id, content) VALUES ('801', 'black & gold') ;
INSERT INTO specification_body (id, content) VALUES ('802', 'graphite') ;
INSERT INTO specification_body (id, content) VALUES ('803', 'huawei matebook d 14"') ;
INSERT INTO specification_body (id, content) VALUES ('804', 'platinum') ;
INSERT INTO specification_body (id, content) VALUES ('805', 'purple') ;
INSERT INTO specification_body (id, content) VALUES ('806', 'carbon') ;
INSERT INTO specification_body (id, content) VALUES ('807', 'matebook x pro 13.9"') ;
INSERT INTO specification_body (id, content) VALUES ('808', 'rtx 2060 / 240gb ssd / 2tb hdd') ;
INSERT INTO specification_body (id, content) VALUES ('809', 'black - g305') ;
