INSERT INTO specification_body (id, content) VALUES ('21', '78863') ;
INSERT INTO specification_body (id, content) VALUES ('0', '1.8 kg') ;
INSERT INTO specification_body (id, content) VALUES ('1', '522 g') ;
INSERT INTO specification_body (id, content) VALUES ('2', '2 kg') ;
INSERT INTO specification_body (id, content) VALUES ('3', '862 g') ;
INSERT INTO specification_body (id, content) VALUES ('4', '721 g') ;
INSERT INTO specification_body (id, content) VALUES ('5', '1.3 kg') ;
INSERT INTO specification_body (id, content) VALUES ('6', '540 g') ;
INSERT INTO specification_body (id, content) VALUES ('7', '259 g') ;
INSERT INTO specification_body (id, content) VALUES ('8', '1.4 kg') ;
INSERT INTO specification_body (id, content) VALUES ('9', '1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('10', '780 g') ;
INSERT INTO specification_body (id, content) VALUES ('11', '640 g') ;
INSERT INTO specification_body (id, content) VALUES ('12', '1.1 kg') ;
INSERT INTO specification_body (id, content) VALUES ('13', 'b2m-00008') ;
INSERT INTO specification_body (id, content) VALUES ('14', '580-adgv') ;
INSERT INTO specification_body (id, content) VALUES ('15', 'l5v-00006') ;
INSERT INTO specification_body (id, content) VALUES ('16', '920-003082') ;
INSERT INTO specification_body (id, content) VALUES ('17', 'ws2-00003') ;
INSERT INTO specification_body (id, content) VALUES ('18', 'n9z-00006') ;
INSERT INTO specification_body (id, content) VALUES ('19', '920-004523') ;
INSERT INTO specification_body (id, content) VALUES ('20', 'g213') ;
INSERT INTO specification_body (id, content) VALUES ('22', '920-007143') ;
INSERT INTO specification_body (id, content) VALUES ('23', '920-008041') ;
INSERT INTO specification_body (id, content) VALUES ('24', 'anb-00006') ;
INSERT INTO specification_body (id, content) VALUES ('25', '920-002524') ;
INSERT INTO specification_body (id, content) VALUES ('26', 'k380') ;
INSERT INTO specification_body (id, content) VALUES ('27', 'm7j-00020') ;
INSERT INTO specification_body (id, content) VALUES ('28', 'microsoft') ;
INSERT INTO specification_body (id, content) VALUES ('29', 'dell') ;
INSERT INTO specification_body (id, content) VALUES ('30', 'logitech') ;
INSERT INTO specification_body (id, content) VALUES ('31', 'victsing') ;
INSERT INTO specification_body (id, content) VALUES ('32', 'tecknet') ;
INSERT INTO specification_body (id, content) VALUES ('33', 'perixx') ;
INSERT INTO specification_body (id, content) VALUES ('34', '60 mb') ;
INSERT INTO specification_body (id, content) VALUES ('35', 'windows 2000, xp p, h, mc, tablet pce^mac os x 10.1.x-10.3.x mac os x 10.0') ;
INSERT INTO specification_body (id, content) VALUES ('36', 'windows xp^windows vista^windows 7') ;
INSERT INTO specification_body (id, content) VALUES ('37', 'windows xp, vista, 7, 8, 10 and later chrome os') ;
INSERT INTO specification_body (id, content) VALUES ('38', 'windows 10/windows 8/windows 8.1/windows 7/windows rt 8.1/windows rt 8') ;
INSERT INTO specification_body (id, content) VALUES ('39', 'windows xp/vista/7^linux 2.6+') ;
INSERT INTO specification_body (id, content) VALUES ('86', '1 jan. 2001') ;
INSERT INTO specification_body (id, content) VALUES ('87', '15 july 2015') ;
INSERT INTO specification_body (id, content) VALUES ('88', '1 jan. 2010') ;
INSERT INTO specification_body (id, content) VALUES ('89', '14 feb. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('90', '2 sept. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('91', '25 jan. 2019') ;
INSERT INTO specification_body (id, content) VALUES ('92', '18 mar. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('93', '1 jan. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('94', '1 oct. 2017') ;
INSERT INTO specification_body (id, content) VALUES ('95', '29 jun. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('96', '23 feb. 2009') ;
INSERT INTO specification_body (id, content) VALUES ('97', '3 sept. 2015') ;
INSERT INTO specification_body (id, content) VALUES ('98', '10 oct. 2016') ;
INSERT INTO specification_body (id, content) VALUES ('79', 'curved') ;
INSERT INTO specification_body (id, content) VALUES ('80', 'standard') ;
INSERT INTO specification_body (id, content) VALUES ('81', 'mini') ;
INSERT INTO specification_body (id, content) VALUES ('82', 'black') ;
INSERT INTO specification_body (id, content) VALUES ('83', 'monotone') ;
INSERT INTO specification_body (id, content) VALUES ('84', 'white') ;
INSERT INTO specification_body (id, content) VALUES ('85', 'dark grey/white') ;
